/**
 * Non-Discourse External Sources
 * 
 * Configuration for EA Forum, LessWrong, and future sources
 * (GitHub Discussions, Hacker News)
 */

import { SourceType } from '@/types';

export interface ExternalSource {
  id: string;
  name: string;
  sourceType: SourceType;
  category: 'ai' | 'oss' | 'cross' | 'crypto';
  description: string;
  logoUrl?: string;
  tier: 1 | 2 | 3;
  enabled: boolean;
  repoRef?: string; // GitHub "owner/repo" format (for sourceType: 'github')
  snapshotSpace?: string; // Snapshot space ID e.g. "aave.eth" (for sourceType: 'snapshot')
  hnQuery?: string; // HN topic terms, used as query + optionalWords (for sourceType: 'hackernews')
  minPoints?: number; // HN points quality threshold (for sourceType: 'hackernews'; default 75)
  lobstersTags?: string; // Comma-separated Lobsters tags (for sourceType: 'lobsters')
  realmsDaoId?: string; // Realms DAO id from lib/realmsClient REALMS_DAOS (for sourceType: 'realms')
}

export const EXTERNAL_SOURCES: ExternalSource[] = [
  // AI Vertical
  {
    id: 'ea-forum',
    name: 'EA Forum',
    sourceType: 'ea-forum',
    category: 'ai',
    description: 'AI safety, funding, grants, Open Philanthropy discussions',
    logoUrl: 'https://forum.effectivealtruism.org/favicon.ico',
    tier: 1,
    enabled: true,
  },
  {
    id: 'lesswrong',
    name: 'LessWrong',
    sourceType: 'lesswrong',
    category: 'ai',
    description: 'AI alignment research, MATS, SERI, rationality',
    logoUrl: 'https://www.lesswrong.com/favicon.ico',
    tier: 1,
    enabled: false, // Blocked by Vercel bot protection on LessWrong's GraphQL endpoint
  },
  // GitHub Discussions — Crypto
  {
    id: 'github-foundry',
    name: 'Foundry',
    sourceType: 'github',
    category: 'crypto',
    description: 'Foundry toolkit for Ethereum development',
    logoUrl: 'https://github.com/foundry-rs.png',
    tier: 2,
    enabled: true,
    repoRef: 'foundry-rs/foundry',
  },
  {
    id: 'github-hardhat',
    name: 'Hardhat',
    sourceType: 'github',
    category: 'crypto',
    description: 'Hardhat Ethereum development environment',
    logoUrl: 'https://github.com/NomicFoundation.png',
    tier: 2,
    enabled: true,
    repoRef: 'NomicFoundation/hardhat',
  },
  {
    id: 'github-reth',
    name: 'Reth',
    sourceType: 'github',
    category: 'crypto',
    description: 'Reth Ethereum execution client discussions',
    logoUrl: 'https://github.com/paradigmxyz.png',
    tier: 2,
    enabled: true,
    repoRef: 'paradigmxyz/reth',
  },
  {
    id: 'github-filecoin-fips',
    name: 'Filecoin FIPs',
    sourceType: 'github',
    category: 'crypto',
    description: 'Filecoin Improvement Proposals discussions',
    logoUrl: 'https://github.com/filecoin-project.png',
    tier: 2,
    enabled: true,
    repoRef: 'filecoin-project/FIPs',
  },
  // GitHub Discussions — AI
  {
    id: 'github-pytorch',
    name: 'PyTorch',
    sourceType: 'github',
    category: 'ai',
    description: 'PyTorch framework discussions and RFCs',
    logoUrl: 'https://github.com/pytorch.png',
    tier: 1,
    enabled: false, // No GitHub Discussions — uses discuss.pytorch.org (Discourse)
    repoRef: 'pytorch/pytorch',
  },
  {
    id: 'github-huggingface-transformers',
    name: 'HuggingFace Transformers',
    sourceType: 'github',
    category: 'ai',
    description: 'Transformers library discussions',
    logoUrl: 'https://github.com/huggingface.png',
    tier: 1,
    enabled: false, // No GitHub Discussions — uses discuss.huggingface.co
    repoRef: 'huggingface/transformers',
  },
  {
    id: 'github-langchain',
    name: 'LangChain',
    sourceType: 'github',
    category: 'ai',
    description: 'LangChain framework discussions',
    logoUrl: 'https://github.com/langchain-ai.png',
    tier: 2,
    enabled: false, // Migrated to LangChain Forum (discuss.langchain.com)
    repoRef: 'langchain-ai/langchain',
  },
  {
    id: 'github-llama-cpp',
    name: 'llama.cpp',
    sourceType: 'github',
    category: 'ai',
    description: 'LLM inference in C/C++ discussions',
    logoUrl: 'https://github.com/ggml-org.png',
    tier: 1,
    enabled: true,
    repoRef: 'ggml-org/llama.cpp',
  },
  {
    id: 'github-vllm',
    name: 'vLLM',
    sourceType: 'github',
    category: 'ai',
    description: 'High-throughput LLM serving engine discussions',
    logoUrl: 'https://github.com/vllm-project.png',
    tier: 2,
    enabled: false, // Discussions migrated away (March 2025)
    repoRef: 'vllm-project/vllm',
  },
  {
    id: 'github-mlflow',
    name: 'MLflow',
    sourceType: 'github',
    category: 'ai',
    description: 'ML lifecycle platform discussions',
    logoUrl: 'https://github.com/mlflow.png',
    tier: 2,
    enabled: true,
    repoRef: 'mlflow/mlflow',
  },
  {
    id: 'github-jax',
    name: 'JAX',
    sourceType: 'github',
    category: 'ai',
    description: 'Google JAX numerical computing discussions',
    logoUrl: 'https://github.com/jax-ml.png',
    tier: 1,
    enabled: true,
    repoRef: 'jax-ml/jax',
  },
  {
    id: 'github-open-webui',
    name: 'Open WebUI',
    sourceType: 'github',
    category: 'ai',
    description: 'Open-source LLM web interface discussions',
    logoUrl: 'https://github.com/open-webui.png',
    tier: 2,
    enabled: true,
    repoRef: 'open-webui/open-webui',
  },
  {
    id: 'github-sglang',
    name: 'SGLang',
    sourceType: 'github',
    category: 'ai',
    description: 'SGLang GitHub Discussions',
    logoUrl: 'https://github.com/sgl-project.png',
    tier: 2,
    enabled: true,
    repoRef: 'sgl-project/sglang',
  },
  {
    id: 'github-triton',
    name: 'Triton (GPU language)',
    sourceType: 'github',
    category: 'ai',
    description: 'Triton (GPU language) GitHub Discussions',
    logoUrl: 'https://github.com/triton-lang.png',
    tier: 2,
    enabled: true,
    repoRef: 'triton-lang/triton',
  },
  {
    id: 'github-haystack',
    name: 'Haystack (deepset)',
    sourceType: 'github',
    category: 'ai',
    description: 'Haystack (deepset) GitHub Discussions',
    logoUrl: 'https://github.com/deepset-ai.png',
    tier: 2,
    enabled: true,
    repoRef: 'deepset-ai/haystack',
  },
  {
    id: 'github-spacy',
    name: 'spaCy',
    sourceType: 'github',
    category: 'ai',
    description: 'spaCy GitHub Discussions',
    logoUrl: 'https://github.com/explosion.png',
    tier: 2,
    enabled: true,
    repoRef: 'explosion/spaCy',
  },
  {
    id: 'github-keras',
    name: 'Keras',
    sourceType: 'github',
    category: 'ai',
    description: 'Keras GitHub Discussions',
    logoUrl: 'https://github.com/keras-team.png',
    tier: 2,
    enabled: true,
    repoRef: 'keras-team/keras',
  },
  {
    id: 'github-onnx',
    name: 'ONNX',
    sourceType: 'github',
    category: 'ai',
    description: 'ONNX GitHub Discussions',
    logoUrl: 'https://github.com/onnx.png',
    tier: 2,
    enabled: true,
    repoRef: 'onnx/onnx',
  },
  {
    id: 'github-bentoml',
    name: 'BentoML',
    sourceType: 'github',
    category: 'ai',
    description: 'BentoML GitHub Discussions',
    logoUrl: 'https://github.com/bentoml.png',
    tier: 2,
    enabled: true,
    repoRef: 'bentoml/BentoML',
  },
  {
    id: 'github-dify',
    name: 'Dify',
    sourceType: 'github',
    category: 'ai',
    description: 'Dify GitHub Discussions',
    logoUrl: 'https://github.com/langgenius.png',
    tier: 2,
    enabled: true,
    repoRef: 'langgenius/dify',
  },
  {
    id: 'github-librechat',
    name: 'LibreChat',
    sourceType: 'github',
    category: 'ai',
    description: 'LibreChat GitHub Discussions',
    logoUrl: 'https://github.com/danny-avila.png',
    tier: 2,
    enabled: true,
    repoRef: 'danny-avila/LibreChat',
  },
  {
    id: 'github-semantic-kernel',
    name: 'Microsoft Semantic Kernel',
    sourceType: 'github',
    category: 'ai',
    description: 'Microsoft Semantic Kernel GitHub Discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 2,
    enabled: true,
    repoRef: 'microsoft/semantic-kernel',
  },
  {
    id: 'github-agent-framework',
    name: 'Microsoft Agent Framework',
    sourceType: 'github',
    category: 'ai',
    description: 'Microsoft Agent Framework GitHub Discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 2,
    enabled: true,
    repoRef: 'microsoft/agent-framework',
  },
  {
    id: 'github-langfuse',
    name: 'Langfuse',
    sourceType: 'github',
    category: 'ai',
    description: 'Langfuse GitHub Discussions',
    logoUrl: 'https://github.com/langfuse.png',
    tier: 2,
    enabled: true,
    repoRef: 'langfuse/langfuse',
  },
  {
    id: 'github-flowise',
    name: 'Flowise',
    sourceType: 'github',
    category: 'ai',
    description: 'Flowise GitHub Discussions',
    logoUrl: 'https://github.com/FlowiseAI.png',
    tier: 2,
    enabled: true,
    repoRef: 'FlowiseAI/Flowise',
  },
  {
    id: 'github-continue',
    name: 'Continue.dev',
    sourceType: 'github',
    category: 'ai',
    description: 'Continue.dev GitHub Discussions',
    logoUrl: 'https://github.com/continuedev.png',
    tier: 2,
    enabled: true,
    repoRef: 'continuedev/continue',
  },
  {
    id: 'github-anthropic-sdk-python',
    name: 'Anthropic anthropic-sdk-python',
    sourceType: 'github',
    category: 'ai',
    description: 'Anthropic anthropic-sdk-python GitHub Discussions',
    logoUrl: 'https://github.com/anthropics.png',
    tier: 2,
    enabled: true,
    repoRef: 'anthropics/anthropic-sdk-python',
  },
  {
    id: 'github-mlx',
    name: 'Apple MLX',
    sourceType: 'github',
    category: 'ai',
    description: 'Apple MLX GitHub Discussions',
    logoUrl: 'https://github.com/ml-explore.png',
    tier: 2,
    enabled: true,
    repoRef: 'ml-explore/mlx',
  },
  {
    id: 'github-diffusers',
    name: 'Hugging Face Diffusers',
    sourceType: 'github',
    category: 'ai',
    description: 'Hugging Face Diffusers GitHub Discussions',
    logoUrl: 'https://github.com/huggingface.png',
    tier: 2,
    enabled: true,
    repoRef: 'huggingface/diffusers',
  },
  {
    id: 'github-smolagents',
    name: 'Hugging Face smolagents',
    sourceType: 'github',
    category: 'ai',
    description: 'Hugging Face smolagents GitHub Discussions',
    logoUrl: 'https://github.com/huggingface.png',
    tier: 2,
    enabled: true,
    repoRef: 'huggingface/smolagents',
  },
  {
    id: 'github-autogen',
    name: 'Microsoft AutoGen',
    sourceType: 'github',
    category: 'ai',
    description: 'Microsoft AutoGen GitHub Discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 2,
    enabled: true,
    repoRef: 'microsoft/autogen',
  },
  {
    id: 'github-dspy',
    name: 'DSPy',
    sourceType: 'github',
    category: 'ai',
    description: 'DSPy GitHub Discussions',
    logoUrl: 'https://github.com/stanfordnlp.png',
    tier: 2,
    enabled: true,
    repoRef: 'stanfordnlp/dspy',
  },
  {
    id: 'github-unsloth',
    name: 'Unsloth',
    sourceType: 'github',
    category: 'ai',
    description: 'Unsloth GitHub Discussions',
    logoUrl: 'https://github.com/unslothai.png',
    tier: 2,
    enabled: true,
    repoRef: 'unslothai/unsloth',
  },
  {
    id: 'github-pytorch-lightning',
    name: 'PyTorch Lightning',
    sourceType: 'github',
    category: 'ai',
    description: 'PyTorch Lightning GitHub Discussions',
    logoUrl: 'https://github.com/Lightning-AI.png',
    tier: 2,
    enabled: true,
    repoRef: 'Lightning-AI/pytorch-lightning',
  },
  {
    id: 'github-trl',
    name: 'Hugging Face TRL',
    sourceType: 'github',
    category: 'ai',
    description: 'Hugging Face TRL GitHub Discussions',
    logoUrl: 'https://github.com/huggingface.png',
    tier: 2,
    enabled: true,
    repoRef: 'huggingface/trl',
  },
  {
    id: 'github-deepspeed',
    name: 'DeepSpeed',
    sourceType: 'github',
    category: 'ai',
    description: 'DeepSpeed GitHub Discussions',
    logoUrl: 'https://github.com/deepspeedai.png',
    tier: 2,
    enabled: true,
    repoRef: 'deepspeedai/DeepSpeed',
  },
  {
    id: 'github-faiss',
    name: 'FAISS',
    sourceType: 'github',
    category: 'ai',
    description: 'FAISS GitHub Discussions',
    logoUrl: 'https://github.com/facebookresearch.png',
    tier: 2,
    enabled: true,
    repoRef: 'facebookresearch/faiss',
  },
  {
    id: 'github-openai-python',
    name: 'OpenAI Python SDK',
    sourceType: 'github',
    category: 'ai',
    description: 'OpenAI Python SDK GitHub Discussions',
    logoUrl: 'https://github.com/openai.png',
    tier: 2,
    enabled: true,
    repoRef: 'openai/openai-python',
  },
  {
    id: 'github-executorch',
    name: 'PyTorch ExecuTorch',
    sourceType: 'github',
    category: 'ai',
    description: 'PyTorch ExecuTorch GitHub Discussions',
    logoUrl: 'https://github.com/pytorch.png',
    tier: 2,
    enabled: true,
    repoRef: 'pytorch/executorch',
  },
  {
    id: 'github-whisper',
    name: 'OpenAI Whisper',
    sourceType: 'github',
    category: 'ai',
    description: 'OpenAI Whisper GitHub Discussions',
    logoUrl: 'https://github.com/openai.png',
    tier: 2,
    enabled: true,
    repoRef: 'openai/whisper',
  },
  // GitHub Discussions — Open Source
  {
    id: 'github-rust-rfcs',
    name: 'Rust RFCs',
    sourceType: 'github',
    category: 'oss',
    description: 'Rust language RFCs and design discussions',
    logoUrl: 'https://github.com/rust-lang.png',
    tier: 1,
    enabled: false, // No GitHub Discussions — uses PRs + Zulip for RFC discussion
    repoRef: 'rust-lang/rfcs',
  },
  {
    id: 'github-nextjs',
    name: 'Next.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Next.js framework discussions',
    logoUrl: 'https://github.com/vercel.png',
    tier: 1,
    enabled: true,
    repoRef: 'vercel/next.js',
  },
  {
    id: 'github-nodejs',
    name: 'Node.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Node.js runtime discussions',
    logoUrl: 'https://github.com/nodejs.png',
    tier: 2,
    enabled: false, // No GitHub Discussions — uses nodejs/help and Discourse
    repoRef: 'nodejs/node',
  },
  {
    id: 'github-godot-proposals',
    name: 'Godot Proposals',
    sourceType: 'github',
    category: 'oss',
    description: 'Godot engine feature proposals and discussions',
    logoUrl: 'https://github.com/godotengine.png',
    tier: 2,
    enabled: true,
    repoRef: 'godotengine/godot-proposals',
  },
  {
    id: 'github-deno',
    name: 'Deno',
    sourceType: 'github',
    category: 'oss',
    description: 'Deno runtime discussions and proposals',
    logoUrl: 'https://github.com/denoland.png',
    tier: 1,
    enabled: true,
    repoRef: 'denoland/deno',
  },
  {
    id: 'github-bun',
    name: 'Bun',
    sourceType: 'github',
    category: 'oss',
    description: 'Bun JavaScript runtime discussions',
    logoUrl: 'https://github.com/oven-sh.png',
    tier: 1,
    enabled: true,
    repoRef: 'oven-sh/bun',
  },
  {
    id: 'github-vue',
    name: 'Vue.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Vue.js framework discussions and RFCs',
    logoUrl: 'https://github.com/vuejs.png',
    tier: 1,
    enabled: true,
    repoRef: 'vuejs/core',
  },
  {
    id: 'github-svelte',
    name: 'Svelte',
    sourceType: 'github',
    category: 'oss',
    description: 'Svelte framework discussions',
    logoUrl: 'https://github.com/sveltejs.png',
    tier: 2,
    enabled: true,
    repoRef: 'sveltejs/svelte',
  },
  {
    id: 'github-tauri',
    name: 'Tauri',
    sourceType: 'github',
    category: 'oss',
    description: 'Tauri desktop app framework discussions',
    logoUrl: 'https://github.com/tauri-apps.png',
    tier: 2,
    enabled: true,
    repoRef: 'tauri-apps/tauri',
  },
  {
    id: 'github-leptos',
    name: 'Leptos',
    sourceType: 'github',
    category: 'oss',
    description: 'Leptos Rust web framework discussions',
    logoUrl: 'https://github.com/leptos-rs.png',
    tier: 3,
    enabled: true,
    repoRef: 'leptos-rs/leptos',
  },
  {
    id: 'github-homebrew',
    name: 'Homebrew',
    sourceType: 'github',
    category: 'oss',
    description: 'Homebrew package manager discussions',
    logoUrl: 'https://github.com/Homebrew.png',
    tier: 2,
    enabled: true,
    repoRef: 'Homebrew/discussions',
  },
  {
    id: 'github-astro-roadmap',
    name: 'Astro',
    sourceType: 'github',
    category: 'oss',
    description: 'Astro web framework roadmap and feature discussions',
    logoUrl: 'https://github.com/withastro.png',
    tier: 1,
    enabled: true,
    repoRef: 'withastro/roadmap',
  },
  {
    id: 'github-ruff',
    name: 'Ruff',
    sourceType: 'github',
    category: 'oss',
    description: 'Ruff Python linter and formatter discussions',
    logoUrl: 'https://github.com/astral-sh.png',
    tier: 1,
    enabled: true,
    repoRef: 'astral-sh/ruff',
  },
  {
    id: 'github-typescript-go',
    name: 'TypeScript Native',
    sourceType: 'github',
    category: 'oss',
    description: 'TypeScript native port (Go) discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 1,
    enabled: true,
    repoRef: 'microsoft/typescript-go',
  },
  {
    id: 'github-golang',
    name: 'Go',
    sourceType: 'github',
    category: 'oss',
    description: 'Go programming language discussions',
    logoUrl: 'https://github.com/golang.png',
    tier: 2,
    enabled: true,
    repoRef: 'golang/go',
  },
  {
    id: 'github-vscode',
    name: 'VS Code',
    sourceType: 'github',
    category: 'oss',
    description: 'Visual Studio Code discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 2,
    enabled: true,
    repoRef: 'microsoft/vscode-discussions',
  },
  {
    id: 'github-oxc',
    name: 'OXC',
    sourceType: 'github',
    category: 'oss',
    description: 'OXC JavaScript toolchain discussions',
    logoUrl: 'https://github.com/oxc-project.png',
    tier: 2,
    enabled: true,
    repoRef: 'oxc-project/oxc',
  },
  {
    id: 'github-gleam',
    name: 'Gleam',
    sourceType: 'github',
    category: 'oss',
    description: 'Gleam programming language discussions',
    logoUrl: 'https://github.com/gleam-lang.png',
    tier: 3,
    enabled: true,
    repoRef: 'gleam-lang/gleam',
  },
  {
    id: 'github-angular',
    name: 'Angular',
    sourceType: 'github',
    category: 'oss',
    description: 'Angular framework discussions',
    logoUrl: 'https://github.com/angular.png',
    tier: 1,
    enabled: true,
    repoRef: 'angular/angular',
  },
  {
    id: 'github-nuxt',
    name: 'Nuxt',
    sourceType: 'github',
    category: 'oss',
    description: 'Nuxt Vue framework discussions',
    logoUrl: 'https://github.com/nuxt.png',
    tier: 1,
    enabled: true,
    repoRef: 'nuxt/nuxt',
  },
  {
    id: 'github-tailwindcss',
    name: 'Tailwind CSS',
    sourceType: 'github',
    category: 'oss',
    description: 'Tailwind CSS utility framework discussions',
    logoUrl: 'https://github.com/tailwindlabs.png',
    tier: 1,
    enabled: true,
    repoRef: 'tailwindlabs/tailwindcss',
  },
  {
    id: 'github-remix',
    name: 'Remix',
    sourceType: 'github',
    category: 'oss',
    description: 'Remix full-stack web framework discussions',
    logoUrl: 'https://github.com/remix-run.png',
    tier: 2,
    enabled: true,
    repoRef: 'remix-run/remix',
  },
  {
    id: 'github-turbo',
    name: 'Turborepo',
    sourceType: 'github',
    category: 'oss',
    description: 'Turborepo monorepo build system discussions',
    logoUrl: 'https://github.com/vercel.png',
    tier: 2,
    enabled: true,
    repoRef: 'vercel/turbo',
  },
  {
    id: 'github-pnpm',
    name: 'pnpm',
    sourceType: 'github',
    category: 'oss',
    description: 'pnpm package manager discussions',
    logoUrl: 'https://github.com/pnpm.png',
    tier: 2,
    enabled: true,
    repoRef: 'pnpm/pnpm',
  },
  {
    id: 'github-shadcn-ui',
    name: 'shadcn/ui',
    sourceType: 'github',
    category: 'oss',
    description: 'shadcn/ui component library discussions',
    logoUrl: 'https://github.com/shadcn-ui.png',
    tier: 2,
    enabled: true,
    repoRef: 'shadcn-ui/ui',
  },
  {
    id: 'github-biome',
    name: 'Biome',
    sourceType: 'github',
    category: 'oss',
    description: 'Biome JS/TS toolchain discussions',
    logoUrl: 'https://github.com/biomejs.png',
    tier: 2,
    enabled: true,
    repoRef: 'biomejs/biome',
  },
  {
    id: 'github-opentofu',
    name: 'OpenTofu',
    sourceType: 'github',
    category: 'oss',
    description: 'OpenTofu infrastructure-as-code discussions',
    logoUrl: 'https://github.com/opentofu.png',
    tier: 2,
    enabled: true,
    repoRef: 'opentofu/opentofu',
  },
  {
    id: 'github-grafana',
    name: 'Grafana',
    sourceType: 'github',
    category: 'oss',
    description: 'Grafana observability platform discussions',
    logoUrl: 'https://github.com/grafana.png',
    tier: 1,
    enabled: true,
    repoRef: 'grafana/grafana',
  },
  {
    id: 'github-prometheus',
    name: 'Prometheus',
    sourceType: 'github',
    category: 'oss',
    description: 'Prometheus monitoring system discussions',
    logoUrl: 'https://github.com/prometheus.png',
    tier: 1,
    enabled: true,
    repoRef: 'prometheus/prometheus',
  },
  {
    id: 'github-tokio',
    name: 'Tokio',
    sourceType: 'github',
    category: 'oss',
    description: 'Tokio Rust async runtime discussions',
    logoUrl: 'https://github.com/tokio-rs.png',
    tier: 2,
    enabled: true,
    repoRef: 'tokio-rs/tokio',
  },
  {
    id: 'github-typst',
    name: 'Typst',
    sourceType: 'github',
    category: 'oss',
    description: 'Typst typesetting system discussions',
    logoUrl: 'https://github.com/typst.png',
    tier: 3,
    enabled: true,
    repoRef: 'typst/typst',
  },
  {
    id: 'github-deno-fresh',
    name: 'Fresh',
    sourceType: 'github',
    category: 'oss',
    description: 'Fresh web framework for Deno discussions',
    logoUrl: 'https://github.com/denoland.png',
    tier: 3,
    enabled: true,
    repoRef: 'denoland/fresh',
  },
  {
    id: 'github-zed',
    name: 'Zed Editor',
    sourceType: 'github',
    category: 'oss',
    description: 'Zed code editor discussions',
    logoUrl: 'https://github.com/zed-industries.png',
    tier: 2,
    enabled: true,
    repoRef: 'zed-industries/zed',
  },
  // Snapshot Governance Spaces
  {
    id: 'snapshot-aave',
    name: 'Aave (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Aave governance proposals and voting',
    logoUrl: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'aave.eth',
  },
  {
    id: 'snapshot-ens',
    name: 'ENS (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'ENS DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/ethereum-name-service-ens-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'ens.eth',
  },
  {
    id: 'snapshot-arbitrum',
    name: 'Arbitrum (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Arbitrum DAO Snapshot voting',
    logoUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'arbitrumfoundation.eth',
  },
  {
    id: 'snapshot-uniswap',
    name: 'Uniswap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Uniswap governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'uniswapgovernance.eth',
  },
  {
    id: 'snapshot-optimism',
    name: 'Optimism (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Optimism Collective governance voting',
    logoUrl: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'opcollective.eth',
  },
  {
    id: 'snapshot-safe',
    name: 'Safe (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Safe DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/safe-safe-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'safe.eth',
  },
  {
    id: 'snapshot-gitcoin',
    name: 'Gitcoin (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Gitcoin DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/gitcoin-gtc-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'gitcoindao.eth',
  },
  {
    id: 'snapshot-lido',
    name: 'Lido (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Lido DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'lido-snapshot.eth',
  },
  {
    id: 'snapshot-balancer',
    name: 'Balancer (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Balancer DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/balancer-bal-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'balancer.eth',
  },
  {
    id: 'snapshot-curve',
    name: 'Curve (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Curve Finance governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'curve.eth',
  },
  {
    id: 'snapshot-compound',
    name: 'Compound (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Compound governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'comp-vote.eth',
  },
  {
    id: 'snapshot-sushiswap',
    name: 'SushiSwap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'SushiSwap DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'sushigov.eth',
  },
  {
    id: 'snapshot-gnosis',
    name: 'Gnosis (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'GnosisDAO governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/662/small/logo_square_simple_300px.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'gnosisdao.eth',
  },
  {
    id: 'snapshot-dydx',
    name: 'dYdX (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'dYdX governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/17500/small/dydx.jpg',
    tier: 2,
    enabled: true,
    snapshotSpace: 'dydxgov.eth',
  },
  {
    id: 'snapshot-frax',
    name: 'Frax Finance (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Frax Finance governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/13423/small/frax.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'frax.eth',
  },
  {
    id: 'snapshot-hop',
    name: 'Hop Protocol (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Hop Protocol governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/25445/small/hop.png',
    tier: 3,
    enabled: true,
    snapshotSpace: 'hop.eth',
  },
  {
    id: 'snapshot-rocketpool',
    name: 'Rocket Pool (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Rocket Pool DAO governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/2090/small/rocket_pool.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'rocketpool-dao.eth',
  },
  // === Sprint 10 additions: cloud-native + DevOps + AI agent frameworks ===
  {
    id: 'github-llamaindex',
    name: 'LlamaIndex',
    sourceType: 'github',
    category: 'ai',
    description: 'LlamaIndex RAG framework discussions',
    logoUrl: 'https://github.com/run-llama.png',
    tier: 1,
    enabled: true,
    repoRef: 'run-llama/llama_index',
  },
  {
    id: 'github-argo-cd',
    name: 'Argo CD',
    sourceType: 'github',
    category: 'oss',
    description: 'Argo CD Kubernetes GitOps discussions',
    logoUrl: 'https://github.com/argoproj.png',
    tier: 1,
    enabled: true,
    repoRef: 'argoproj/argo-cd',
  },
  {
    id: 'github-cilium',
    name: 'Cilium',
    sourceType: 'github',
    category: 'oss',
    description: 'Cilium eBPF-based networking and security discussions',
    logoUrl: 'https://github.com/cilium.png',
    tier: 1,
    enabled: true,
    repoRef: 'cilium/cilium',
  },
  {
    id: 'github-otel-collector',
    name: 'OpenTelemetry Collector',
    sourceType: 'github',
    category: 'oss',
    description: 'OpenTelemetry Collector discussions (telemetry pipelines)',
    logoUrl: 'https://github.com/open-telemetry.png',
    tier: 1,
    enabled: true,
    repoRef: 'open-telemetry/opentelemetry-collector',
  },
  {
    id: 'github-vite',
    name: 'Vite',
    sourceType: 'github',
    category: 'oss',
    description: 'Vite frontend build tool discussions',
    logoUrl: 'https://github.com/vitejs.png',
    tier: 1,
    enabled: true,
    repoRef: 'vitejs/vite',
  },
  {
    id: 'github-tanstack-query',
    name: 'TanStack Query',
    sourceType: 'github',
    category: 'oss',
    description: 'TanStack Query (React Query / Vue Query / etc.) discussions',
    logoUrl: 'https://github.com/TanStack.png',
    tier: 1,
    enabled: true,
    repoRef: 'TanStack/query',
  },
  {
    id: 'github-neovim',
    name: 'Neovim',
    sourceType: 'github',
    category: 'oss',
    description: 'Neovim editor discussions',
    logoUrl: 'https://github.com/neovim.png',
    tier: 1,
    enabled: true,
    repoRef: 'neovim/neovim',
  },
  {
    id: 'github-duckdb',
    name: 'DuckDB',
    sourceType: 'github',
    category: 'oss',
    description: 'DuckDB embedded analytical database discussions',
    logoUrl: 'https://github.com/duckdb.png',
    tier: 1,
    enabled: true,
    repoRef: 'duckdb/duckdb',
  },
  {
    id: 'github-clickhouse',
    name: 'ClickHouse',
    sourceType: 'github',
    category: 'oss',
    description: 'ClickHouse columnar database discussions',
    logoUrl: 'https://github.com/ClickHouse.png',
    tier: 1,
    enabled: true,
    repoRef: 'ClickHouse/ClickHouse',
  },
  {
    id: 'github-supabase',
    name: 'Supabase',
    sourceType: 'github',
    category: 'oss',
    description: 'Supabase open-source Firebase alternative discussions',
    logoUrl: 'https://github.com/supabase.png',
    tier: 1,
    enabled: true,
    repoRef: 'supabase/supabase',
  },
  {
    id: 'github-flux2',
    name: 'Flux CD',
    sourceType: 'github',
    category: 'oss',
    description: 'Flux GitOps for Kubernetes discussions',
    logoUrl: 'https://github.com/fluxcd.png',
    tier: 2,
    enabled: true,
    repoRef: 'fluxcd/flux2',
  },
  {
    id: 'github-keda',
    name: 'KEDA',
    sourceType: 'github',
    category: 'oss',
    description: 'KEDA event-driven Kubernetes autoscaling discussions',
    logoUrl: 'https://github.com/kedacore.png',
    tier: 2,
    enabled: true,
    repoRef: 'kedacore/keda',
  },
  {
    id: 'github-k3s',
    name: 'k3s',
    sourceType: 'github',
    category: 'oss',
    description: 'k3s lightweight Kubernetes discussions',
    logoUrl: 'https://github.com/k3s-io.png',
    tier: 2,
    enabled: true,
    repoRef: 'k3s-io/k3s',
  },
  {
    id: 'github-longhorn',
    name: 'Longhorn',
    sourceType: 'github',
    category: 'oss',
    description: 'Longhorn distributed block storage for Kubernetes',
    logoUrl: 'https://github.com/longhorn.png',
    tier: 2,
    enabled: true,
    repoRef: 'longhorn/longhorn',
  },
  {
    id: 'github-pulumi',
    name: 'Pulumi',
    sourceType: 'github',
    category: 'oss',
    description: 'Pulumi infrastructure-as-code discussions',
    logoUrl: 'https://github.com/pulumi.png',
    tier: 2,
    enabled: true,
    repoRef: 'pulumi/pulumi',
  },
  {
    id: 'github-crossplane',
    name: 'Crossplane',
    sourceType: 'github',
    category: 'oss',
    description: 'Crossplane GitHub Discussions',
    logoUrl: 'https://github.com/crossplane.png',
    tier: 2,
    enabled: true,
    repoRef: 'crossplane/crossplane',
  },
  {
    id: 'github-trino',
    name: 'Trino',
    sourceType: 'github',
    category: 'oss',
    description: 'Trino GitHub Discussions',
    logoUrl: 'https://github.com/trinodb.png',
    tier: 2,
    enabled: true,
    repoRef: 'trinodb/trino',
  },
  {
    id: 'github-prefect',
    name: 'Prefect',
    sourceType: 'github',
    category: 'oss',
    description: 'Prefect GitHub Discussions',
    logoUrl: 'https://github.com/PrefectHQ.png',
    tier: 2,
    enabled: true,
    repoRef: 'PrefectHQ/prefect',
  },
  {
    id: 'github-airbyte',
    name: 'Airbyte',
    sourceType: 'github',
    category: 'oss',
    description: 'Airbyte GitHub Discussions',
    logoUrl: 'https://github.com/airbytehq.png',
    tier: 2,
    enabled: true,
    repoRef: 'airbytehq/airbyte',
  },
  {
    id: 'github-dagster',
    name: 'Dagster',
    sourceType: 'github',
    category: 'oss',
    description: 'Dagster GitHub Discussions',
    logoUrl: 'https://github.com/dagster-io.png',
    tier: 2,
    enabled: true,
    repoRef: 'dagster-io/dagster',
  },
  {
    id: 'github-linkerd2',
    name: 'Linkerd',
    sourceType: 'github',
    category: 'oss',
    description: 'Linkerd GitHub Discussions',
    logoUrl: 'https://github.com/linkerd.png',
    tier: 2,
    enabled: true,
    repoRef: 'linkerd/linkerd2',
  },
  {
    id: 'github-fluent-bit',
    name: 'Fluent Bit',
    sourceType: 'github',
    category: 'oss',
    description: 'Fluent Bit GitHub Discussions',
    logoUrl: 'https://github.com/fluent.png',
    tier: 2,
    enabled: true,
    repoRef: 'fluent/fluent-bit',
  },
  {
    id: 'github-webpack',
    name: 'Webpack',
    sourceType: 'github',
    category: 'oss',
    description: 'Webpack GitHub Discussions',
    logoUrl: 'https://github.com/webpack.png',
    tier: 2,
    enabled: true,
    repoRef: 'webpack/webpack',
  },
  {
    id: 'github-solid',
    name: 'SolidJS',
    sourceType: 'github',
    category: 'oss',
    description: 'SolidJS GitHub Discussions',
    logoUrl: 'https://github.com/solidjs.png',
    tier: 2,
    enabled: true,
    repoRef: 'solidjs/solid',
  },
  {
    id: 'github-solid-start',
    name: 'SolidStart',
    sourceType: 'github',
    category: 'oss',
    description: 'SolidStart GitHub Discussions',
    logoUrl: 'https://github.com/solidjs.png',
    tier: 2,
    enabled: true,
    repoRef: 'solidjs/solid-start',
  },
  {
    id: 'github-storybook',
    name: 'Storybook',
    sourceType: 'github',
    category: 'oss',
    description: 'Storybook GitHub Discussions',
    logoUrl: 'https://github.com/storybookjs.png',
    tier: 2,
    enabled: true,
    repoRef: 'storybookjs/storybook',
  },
  {
    id: 'github-rspack',
    name: 'Rspack',
    sourceType: 'github',
    category: 'oss',
    description: 'Rspack GitHub Discussions',
    logoUrl: 'https://github.com/web-infra-dev.png',
    tier: 2,
    enabled: true,
    repoRef: 'web-infra-dev/rspack',
  },
  {
    id: 'github-rolldown',
    name: 'Rolldown',
    sourceType: 'github',
    category: 'oss',
    description: 'Rolldown GitHub Discussions',
    logoUrl: 'https://github.com/rolldown.png',
    tier: 2,
    enabled: true,
    repoRef: 'rolldown/rolldown',
  },
  {
    id: 'github-discussions-and-proposals',
    name: 'React Native Community Discussions & Proposals',
    sourceType: 'github',
    category: 'oss',
    description: 'React Native Community Discussions & Proposals GitHub Discussions',
    logoUrl: 'https://github.com/react-native-community.png',
    tier: 2,
    enabled: true,
    repoRef: 'react-native-community/discussions-and-proposals',
  },
  {
    id: 'github-react-compiler',
    name: 'React Compiler Working Group',
    sourceType: 'github',
    category: 'oss',
    description: 'React Compiler Working Group GitHub Discussions',
    logoUrl: 'https://github.com/reactwg.png',
    tier: 2,
    enabled: true,
    repoRef: 'reactwg/react-compiler',
  },
  {
    id: 'github-symfony',
    name: 'Symfony',
    sourceType: 'github',
    category: 'oss',
    description: 'Symfony GitHub Discussions',
    logoUrl: 'https://github.com/symfony.png',
    tier: 2,
    enabled: true,
    repoRef: 'symfony/symfony',
  },
  {
    id: 'github-framework',
    name: 'Laravel Framework',
    sourceType: 'github',
    category: 'oss',
    description: 'Laravel Framework GitHub Discussions',
    logoUrl: 'https://github.com/laravel.png',
    tier: 2,
    enabled: true,
    repoRef: 'laravel/framework',
  },
  {
    id: 'github-gutenberg',
    name: 'WordPress Gutenberg',
    sourceType: 'github',
    category: 'oss',
    description: 'WordPress Gutenberg GitHub Discussions',
    logoUrl: 'https://github.com/WordPress.png',
    tier: 2,
    enabled: true,
    repoRef: 'WordPress/gutenberg',
  },
  {
    id: 'github-fastapi',
    name: 'FastAPI',
    sourceType: 'github',
    category: 'oss',
    description: 'FastAPI GitHub Discussions',
    logoUrl: 'https://github.com/fastapi.png',
    tier: 2,
    enabled: true,
    repoRef: 'fastapi/fastapi',
  },
  {
    id: 'github-sqlmodel',
    name: 'SQLModel',
    sourceType: 'github',
    category: 'oss',
    description: 'SQLModel GitHub Discussions',
    logoUrl: 'https://github.com/fastapi.png',
    tier: 2,
    enabled: true,
    repoRef: 'fastapi/sqlmodel',
  },
  {
    id: 'github-datafusion',
    name: 'Apache DataFusion',
    sourceType: 'github',
    category: 'oss',
    description: 'Apache DataFusion GitHub Discussions',
    logoUrl: 'https://github.com/apache.png',
    tier: 2,
    enabled: true,
    repoRef: 'apache/datafusion',
  },
  {
    id: 'github-typer',
    name: 'Typer',
    sourceType: 'github',
    category: 'oss',
    description: 'Typer GitHub Discussions',
    logoUrl: 'https://github.com/tiangolo.png',
    tier: 2,
    enabled: true,
    repoRef: 'tiangolo/typer',
  },
  {
    id: 'github-full-stack-fastapi-template',
    name: 'Full Stack FastAPI Template',
    sourceType: 'github',
    category: 'oss',
    description: 'Full Stack FastAPI Template GitHub Discussions',
    logoUrl: 'https://github.com/tiangolo.png',
    tier: 2,
    enabled: true,
    repoRef: 'tiangolo/full-stack-fastapi-template',
  },
  {
    id: 'github-prisma',
    name: 'Prisma',
    sourceType: 'github',
    category: 'oss',
    description: 'Prisma GitHub Discussions',
    logoUrl: 'https://github.com/prisma.png',
    tier: 2,
    enabled: true,
    repoRef: 'prisma/prisma',
  },
  {
    id: 'github-roslyn',
    name: 'dotnet/roslyn',
    sourceType: 'github',
    category: 'oss',
    description: 'dotnet/roslyn GitHub Discussions',
    logoUrl: 'https://github.com/dotnet.png',
    tier: 2,
    enabled: true,
    repoRef: 'dotnet/roslyn',
  },
  // Hacker News — per-vertical topic feeds (Algolia API, no auth)
  {
    id: 'hn-ai',
    name: 'Hacker News · AI',
    sourceType: 'hackernews',
    category: 'ai',
    description: 'Top HN stories on LLMs, AI models, and ML tooling',
    logoUrl: 'https://news.ycombinator.com/favicon.ico',
    tier: 1,
    enabled: true,
    hnQuery: 'LLM GPT transformer inference Llama Anthropic OpenAI Mistral embeddings RAG finetuning Gemini Claude diffusion',
    minPoints: 75,
  },
  {
    id: 'hn-oss',
    name: 'Hacker News · Open Source',
    sourceType: 'hackernews',
    category: 'oss',
    description: 'Top HN stories on open-source projects, maintainers, and licensing',
    logoUrl: 'https://news.ycombinator.com/favicon.ico',
    tier: 1,
    enabled: true,
    hnQuery: 'open-source FOSS maintainer copyleft GPL AGPL self-hosted upstream kernel Linux',
    minPoints: 75,
  },
  {
    id: 'hn-crypto',
    name: 'Hacker News · Crypto',
    sourceType: 'hackernews',
    category: 'crypto',
    description: 'Top HN stories on Ethereum, Bitcoin, rollups, and onchain protocols',
    logoUrl: 'https://news.ycombinator.com/favicon.ico',
    tier: 2,
    enabled: true,
    hnQuery: 'Ethereum Bitcoin rollup zero-knowledge DeFi stablecoin onchain Solana zk blockchain',
    minPoints: 75,
  },
  // Snapshot governance spaces — Sprint 18 bulk additions (confirmed active proposals)
  {
    id: 'snapshot-morpho',
    name: 'Morpho (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Morpho DAO governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/29837/small/Morpho-token-icon.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'morpho.eth',
  },
  {
    id: 'snapshot-starknet',
    name: 'Starknet (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Starknet governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/26433/small/starknet.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'starknet.eth',
  },
  {
    id: 'snapshot-apecoin',
    name: 'ApeCoin (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'ApeCoin DAO governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/24383/small/apecoin.jpg',
    tier: 2,
    enabled: true,
    snapshotSpace: 'apecoin.eth',
  },
  {
    id: 'snapshot-spark',
    name: 'Spark (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Spark governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'sparkfi.eth',
  },
  {
    id: 'snapshot-pancakeswap',
    name: 'PancakeSwap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'PancakeSwap governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'cakevote.eth',
  },
  {
    id: 'snapshot-stargate-dao',
    name: 'Stargate DAO (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Stargate DAO governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'stgdao.eth',
  },
  {
    id: 'snapshot-convex-finance',
    name: 'Convex Finance (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Convex Finance governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'cvx.eth',
  },
  {
    id: 'snapshot-1inch-network',
    name: '1inch Network (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: '1inch Network governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: '1inch.eth',
  },
  {
    id: 'snapshot-synthetix',
    name: 'Synthetix (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Synthetix governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'snxgov.eth',
  },
  {
    id: 'snapshot-gmx',
    name: 'GMX (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'GMX governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'gmx.eth',
  },
  {
    id: 'snapshot-yearn-finance',
    name: 'Yearn Finance (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Yearn Finance governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'veyfi.eth',
  },
  {
    id: 'snapshot-olympus-dao',
    name: 'Olympus DAO (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Olympus DAO governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'olympusdao.eth',
  },
  {
    id: 'snapshot-alchemix',
    name: 'Alchemix (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Alchemix governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'alchemixstakers.eth',
  },
  {
    id: 'snapshot-mantle-network-bitdao',
    name: 'Mantle Network (BitDAO) (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Mantle Network (BitDAO) governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'bitdao.eth',
  },
  {
    id: 'snapshot-instadapp',
    name: 'Instadapp (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Instadapp governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'instadapp-gov.eth',
  },
  {
    id: 'snapshot-juiceboxdao',
    name: 'JuiceboxDAO (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'JuiceboxDAO governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'jbdao.eth',
  },
  {
    id: 'snapshot-shapeshift-dao',
    name: 'ShapeShift DAO (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'ShapeShift DAO governance proposals (Snapshot)',
    tier: 2,
    enabled: true,
    snapshotSpace: 'shapeshiftdao.eth',
  },
  // Lobsters — per-vertical tag feeds (public JSON, no auth). Crypto skipped (low volume).
  {
    id: 'lobsters-ai',
    name: 'Lobsters · AI',
    sourceType: 'lobsters',
    category: 'ai',
    description: 'Recent Lobsters discussions tagged AI/ML',
    logoUrl: 'https://lobste.rs/favicon.ico',
    tier: 2,
    enabled: true,
    lobstersTags: 'ai',
  },
  {
    id: 'lobsters-oss',
    name: 'Lobsters · Open Source',
    sourceType: 'lobsters',
    category: 'oss',
    description: 'Recent Lobsters discussions on programming and open source',
    logoUrl: 'https://lobste.rs/favicon.ico',
    tier: 2,
    enabled: true,
    lobstersTags: 'programming,rust,go,python,javascript,web,devops,compsci',
  },
  // Realms (SPL Governance) — on-chain Solana DAO proposals
  {
    id: 'realms-pyth',
    name: 'Pyth Governance (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Pyth Network on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/pyth-network.jpg',
    tier: 1,
    enabled: true,
    realmsDaoId: 'pyth',
  },
  {
    id: 'realms-jito',
    name: 'Jito DAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Jito DAO on-chain governance proposals (JIPs)',
    logoUrl: 'https://icons.llama.fi/jito-liquid-staking.jpg',
    tier: 1,
    enabled: true,
    realmsDaoId: 'jito',
  },
  {
    id: 'realms-marinade',
    name: 'Marinade DAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Marinade on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/marinade-finance.jpg',
    tier: 1,
    enabled: true,
    realmsDaoId: 'marinade',
  },
  {
    id: 'realms-bonk',
    name: 'BonkDAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'BonkDAO on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/bonkswap.jpg',
    tier: 2,
    enabled: true,
    realmsDaoId: 'bonk',
  },
  {
    id: 'realms-orca',
    name: 'Orca DAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Orca DAO on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/orca.jpg',
    tier: 2,
    enabled: true,
    realmsDaoId: 'orca',
  },
  {
    id: 'realms-drift',
    name: 'Drift DAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Drift Protocol on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/drift-trade.jpg',
    tier: 2,
    enabled: true,
    realmsDaoId: 'drift',
  },
  {
    id: 'realms-parcl',
    name: 'Parcl DAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Parcl DAO on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/parcl.jpg',
    tier: 2,
    enabled: true,
    realmsDaoId: 'parcl',
  },
  {
    id: 'realms-metaplex',
    name: 'Metaplex DAO (Realms)',
    sourceType: 'realms',
    category: 'crypto',
    description: 'Metaplex DAO on-chain governance proposals',
    logoUrl: 'https://icons.llama.fi/metaplex.png',
    tier: 2,
    enabled: true,
    realmsDaoId: 'metaplex',
  },
];

export function getEnabledExternalSources(): ExternalSource[] {
  return EXTERNAL_SOURCES.filter(s => s.enabled);
}

export function getExternalSourcesByCategory(category: 'ai' | 'oss' | 'cross'): ExternalSource[] {
  return EXTERNAL_SOURCES.filter(s => s.category === category && s.enabled);
}
