/**
 * Non-Discourse External Sources
 * 
 * Configuration for EA Forum, LessWrong, and future sources
 * (GitHub Discussions, Hacker News)
 */

import { SourceType } from '@/types';

export interface ExternalSource {
  id: string;
  name: string;
  sourceType: SourceType;
  category: 'ai' | 'oss' | 'cross' | 'crypto';
  description: string;
  logoUrl?: string;
  tier: 1 | 2 | 3;
  enabled: boolean;
  repoRef?: string; // GitHub "owner/repo" format (for sourceType: 'github')
  snapshotSpace?: string; // Snapshot space ID e.g. "aave.eth" (for sourceType: 'snapshot')
}

export const EXTERNAL_SOURCES: ExternalSource[] = [
  // AI Vertical
  {
    id: 'ea-forum',
    name: 'EA Forum',
    sourceType: 'ea-forum',
    category: 'ai',
    description: 'AI safety, funding, grants, Open Philanthropy discussions',
    logoUrl: 'https://forum.effectivealtruism.org/favicon.ico',
    tier: 1,
    enabled: true,
  },
  {
    id: 'lesswrong',
    name: 'LessWrong',
    sourceType: 'lesswrong',
    category: 'ai',
    description: 'AI alignment research, MATS, SERI, rationality',
    logoUrl: 'https://www.lesswrong.com/favicon.ico',
    tier: 1,
    enabled: false, // Blocked by Vercel bot protection on LessWrong's GraphQL endpoint
  },
  // GitHub Discussions — Crypto
  {
    id: 'github-ethereum-eips',
    name: 'Ethereum EIPs',
    sourceType: 'github',
    category: 'crypto',
    description: 'Ethereum Improvement Proposals discussions',
    logoUrl: 'https://github.com/ethereum.png',
    tier: 1,
    enabled: true,
    repoRef: 'ethereum/EIPs',
  },
  {
    id: 'github-ethereum-pm',
    name: 'Ethereum PM',
    sourceType: 'github',
    category: 'crypto',
    description: 'Ethereum project management and ACD calls',
    logoUrl: 'https://github.com/ethereum.png',
    tier: 2,
    enabled: true,
    repoRef: 'ethereum/pm',
  },
  {
    id: 'github-foundry',
    name: 'Foundry',
    sourceType: 'github',
    category: 'crypto',
    description: 'Foundry toolkit for Ethereum development',
    logoUrl: 'https://github.com/foundry-rs.png',
    tier: 2,
    enabled: true,
    repoRef: 'foundry-rs/foundry',
  },
  {
    id: 'github-hardhat',
    name: 'Hardhat',
    sourceType: 'github',
    category: 'crypto',
    description: 'Hardhat Ethereum development environment',
    logoUrl: 'https://github.com/NomicFoundation.png',
    tier: 2,
    enabled: true,
    repoRef: 'NomicFoundation/hardhat',
  },
  // GitHub Discussions — AI
  {
    id: 'github-pytorch',
    name: 'PyTorch',
    sourceType: 'github',
    category: 'ai',
    description: 'PyTorch framework discussions and RFCs',
    logoUrl: 'https://github.com/pytorch.png',
    tier: 1,
    enabled: true,
    repoRef: 'pytorch/pytorch',
  },
  {
    id: 'github-huggingface-transformers',
    name: 'HuggingFace Transformers',
    sourceType: 'github',
    category: 'ai',
    description: 'Transformers library discussions',
    logoUrl: 'https://github.com/huggingface.png',
    tier: 1,
    enabled: true,
    repoRef: 'huggingface/transformers',
  },
  {
    id: 'github-langchain',
    name: 'LangChain',
    sourceType: 'github',
    category: 'ai',
    description: 'LangChain framework discussions',
    logoUrl: 'https://github.com/langchain-ai.png',
    tier: 2,
    enabled: true,
    repoRef: 'langchain-ai/langchain',
  },
  {
    id: 'github-llama-cpp',
    name: 'llama.cpp',
    sourceType: 'github',
    category: 'ai',
    description: 'LLM inference in C/C++ discussions',
    logoUrl: 'https://github.com/ggerganov.png',
    tier: 1,
    enabled: true,
    repoRef: 'ggerganov/llama.cpp',
  },
  {
    id: 'github-vllm',
    name: 'vLLM',
    sourceType: 'github',
    category: 'ai',
    description: 'High-throughput LLM serving engine discussions',
    logoUrl: 'https://github.com/vllm-project.png',
    tier: 2,
    enabled: true,
    repoRef: 'vllm-project/vllm',
  },
  {
    id: 'github-mlflow',
    name: 'MLflow',
    sourceType: 'github',
    category: 'ai',
    description: 'ML lifecycle platform discussions',
    logoUrl: 'https://github.com/mlflow.png',
    tier: 2,
    enabled: true,
    repoRef: 'mlflow/mlflow',
  },
  // GitHub Discussions — Open Source
  {
    id: 'github-rust-rfcs',
    name: 'Rust RFCs',
    sourceType: 'github',
    category: 'oss',
    description: 'Rust language RFCs and design discussions',
    logoUrl: 'https://github.com/rust-lang.png',
    tier: 1,
    enabled: true,
    repoRef: 'rust-lang/rfcs',
  },
  {
    id: 'github-nextjs',
    name: 'Next.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Next.js framework discussions',
    logoUrl: 'https://github.com/vercel.png',
    tier: 1,
    enabled: true,
    repoRef: 'vercel/next.js',
  },
  {
    id: 'github-nodejs',
    name: 'Node.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Node.js runtime discussions',
    logoUrl: 'https://github.com/nodejs.png',
    tier: 2,
    enabled: true,
    repoRef: 'nodejs/node',
  },
  {
    id: 'github-godot-proposals',
    name: 'Godot Proposals',
    sourceType: 'github',
    category: 'oss',
    description: 'Godot engine feature proposals and discussions',
    logoUrl: 'https://github.com/godotengine.png',
    tier: 2,
    enabled: true,
    repoRef: 'godotengine/godot-proposals',
  },
  {
    id: 'github-deno',
    name: 'Deno',
    sourceType: 'github',
    category: 'oss',
    description: 'Deno runtime discussions and proposals',
    logoUrl: 'https://github.com/denoland.png',
    tier: 1,
    enabled: true,
    repoRef: 'denoland/deno',
  },
  {
    id: 'github-bun',
    name: 'Bun',
    sourceType: 'github',
    category: 'oss',
    description: 'Bun JavaScript runtime discussions',
    logoUrl: 'https://github.com/oven-sh.png',
    tier: 1,
    enabled: true,
    repoRef: 'oven-sh/bun',
  },
  {
    id: 'github-vue',
    name: 'Vue.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Vue.js framework discussions and RFCs',
    logoUrl: 'https://github.com/vuejs.png',
    tier: 1,
    enabled: true,
    repoRef: 'vuejs/core',
  },
  {
    id: 'github-svelte',
    name: 'Svelte',
    sourceType: 'github',
    category: 'oss',
    description: 'Svelte framework discussions',
    logoUrl: 'https://github.com/sveltejs.png',
    tier: 2,
    enabled: true,
    repoRef: 'sveltejs/svelte',
  },
  {
    id: 'github-tauri',
    name: 'Tauri',
    sourceType: 'github',
    category: 'oss',
    description: 'Tauri desktop app framework discussions',
    logoUrl: 'https://github.com/tauri-apps.png',
    tier: 2,
    enabled: true,
    repoRef: 'tauri-apps/tauri',
  },
  {
    id: 'github-leptos',
    name: 'Leptos',
    sourceType: 'github',
    category: 'oss',
    description: 'Leptos Rust web framework discussions',
    logoUrl: 'https://github.com/leptos-rs.png',
    tier: 3,
    enabled: true,
    repoRef: 'leptos-rs/leptos',
  },
  {
    id: 'github-homebrew',
    name: 'Homebrew',
    sourceType: 'github',
    category: 'oss',
    description: 'Homebrew package manager discussions',
    logoUrl: 'https://github.com/Homebrew.png',
    tier: 2,
    enabled: true,
    repoRef: 'Homebrew/discussions',
  },
  // Snapshot Governance Spaces
  {
    id: 'snapshot-aave',
    name: 'Aave (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Aave governance proposals and voting',
    logoUrl: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'aave.eth',
  },
  {
    id: 'snapshot-ens',
    name: 'ENS (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'ENS DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/ethereum-name-service-ens-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'ens.eth',
  },
  {
    id: 'snapshot-arbitrum',
    name: 'Arbitrum (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Arbitrum DAO Snapshot voting',
    logoUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'arbitrumfoundation.eth',
  },
  {
    id: 'snapshot-uniswap',
    name: 'Uniswap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Uniswap governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'uniswapgovernance.eth',
  },
  {
    id: 'snapshot-optimism',
    name: 'Optimism (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Optimism Collective governance voting',
    logoUrl: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'opcollective.eth',
  },
  {
    id: 'snapshot-safe',
    name: 'Safe (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Safe DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/safe-safe-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'safe.eth',
  },
  {
    id: 'snapshot-gitcoin',
    name: 'Gitcoin (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Gitcoin DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/gitcoin-gtc-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'gitcoindao.eth',
  },
  {
    id: 'snapshot-lido',
    name: 'Lido (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Lido DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'lido-snapshot.eth',
  },
  {
    id: 'snapshot-balancer',
    name: 'Balancer (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Balancer DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/balancer-bal-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'balancer.eth',
  },
  {
    id: 'snapshot-curve',
    name: 'Curve (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Curve Finance governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'curve.eth',
  },
  {
    id: 'snapshot-compound',
    name: 'Compound (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Compound governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'comp-vote.eth',
  },
  {
    id: 'snapshot-sushiswap',
    name: 'SushiSwap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'SushiSwap DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'sushigov.eth',
  },
  // Future sources (disabled for now)
  // {
  //   id: 'hackernews',
  //   name: 'Hacker News',
  //   sourceType: 'hackernews',
  //   category: 'cross',
  //   description: 'Tech news and discussions',
  //   logoUrl: 'https://news.ycombinator.com/favicon.ico',
  //   tier: 2,
  //   enabled: false,
  // },
];

export function getEnabledExternalSources(): ExternalSource[] {
  return EXTERNAL_SOURCES.filter(s => s.enabled);
}

export function getExternalSourcesByCategory(category: 'ai' | 'oss' | 'cross'): ExternalSource[] {
  return EXTERNAL_SOURCES.filter(s => s.category === category && s.enabled);
}
