/**
 * Non-Discourse External Sources
 * 
 * Configuration for EA Forum, LessWrong, and future sources
 * (GitHub Discussions, Hacker News)
 */

import { SourceType } from '@/types';

export interface ExternalSource {
  id: string;
  name: string;
  sourceType: SourceType;
  category: 'ai' | 'oss' | 'cross' | 'crypto';
  description: string;
  logoUrl?: string;
  tier: 1 | 2 | 3;
  enabled: boolean;
  repoRef?: string; // GitHub "owner/repo" format (for sourceType: 'github')
  snapshotSpace?: string; // Snapshot space ID e.g. "aave.eth" (for sourceType: 'snapshot')
}

export const EXTERNAL_SOURCES: ExternalSource[] = [
  // AI Vertical
  {
    id: 'ea-forum',
    name: 'EA Forum',
    sourceType: 'ea-forum',
    category: 'ai',
    description: 'AI safety, funding, grants, Open Philanthropy discussions',
    logoUrl: 'https://forum.effectivealtruism.org/favicon.ico',
    tier: 1,
    enabled: true,
  },
  {
    id: 'lesswrong',
    name: 'LessWrong',
    sourceType: 'lesswrong',
    category: 'ai',
    description: 'AI alignment research, MATS, SERI, rationality',
    logoUrl: 'https://www.lesswrong.com/favicon.ico',
    tier: 1,
    enabled: false, // Blocked by Vercel bot protection on LessWrong's GraphQL endpoint
  },
  // GitHub Discussions — Crypto
  {
    id: 'github-ethereum-eips',
    name: 'Ethereum EIPs',
    sourceType: 'github',
    category: 'crypto',
    description: 'Ethereum Improvement Proposals discussions',
    logoUrl: 'https://github.com/ethereum.png',
    tier: 1,
    enabled: true,
    repoRef: 'ethereum/EIPs',
  },
  {
    id: 'github-ethereum-pm',
    name: 'Ethereum PM',
    sourceType: 'github',
    category: 'crypto',
    description: 'Ethereum project management and ACD calls',
    logoUrl: 'https://github.com/ethereum.png',
    tier: 2,
    enabled: true,
    repoRef: 'ethereum/pm',
  },
  {
    id: 'github-foundry',
    name: 'Foundry',
    sourceType: 'github',
    category: 'crypto',
    description: 'Foundry toolkit for Ethereum development',
    logoUrl: 'https://github.com/foundry-rs.png',
    tier: 2,
    enabled: true,
    repoRef: 'foundry-rs/foundry',
  },
  {
    id: 'github-hardhat',
    name: 'Hardhat',
    sourceType: 'github',
    category: 'crypto',
    description: 'Hardhat Ethereum development environment',
    logoUrl: 'https://github.com/NomicFoundation.png',
    tier: 2,
    enabled: true,
    repoRef: 'NomicFoundation/hardhat',
  },
  {
    id: 'github-reth',
    name: 'Reth',
    sourceType: 'github',
    category: 'crypto',
    description: 'Reth Ethereum execution client discussions',
    logoUrl: 'https://github.com/paradigmxyz.png',
    tier: 2,
    enabled: true,
    repoRef: 'paradigmxyz/reth',
  },
  {
    id: 'github-filecoin-fips',
    name: 'Filecoin FIPs',
    sourceType: 'github',
    category: 'crypto',
    description: 'Filecoin Improvement Proposals discussions',
    logoUrl: 'https://github.com/filecoin-project.png',
    tier: 2,
    enabled: true,
    repoRef: 'filecoin-project/FIPs',
  },
  // GitHub Discussions — AI
  {
    id: 'github-pytorch',
    name: 'PyTorch',
    sourceType: 'github',
    category: 'ai',
    description: 'PyTorch framework discussions and RFCs',
    logoUrl: 'https://github.com/pytorch.png',
    tier: 1,
    enabled: false, // No GitHub Discussions — uses discuss.pytorch.org (Discourse)
    repoRef: 'pytorch/pytorch',
  },
  {
    id: 'github-huggingface-transformers',
    name: 'HuggingFace Transformers',
    sourceType: 'github',
    category: 'ai',
    description: 'Transformers library discussions',
    logoUrl: 'https://github.com/huggingface.png',
    tier: 1,
    enabled: false, // No GitHub Discussions — uses discuss.huggingface.co
    repoRef: 'huggingface/transformers',
  },
  {
    id: 'github-langchain',
    name: 'LangChain',
    sourceType: 'github',
    category: 'ai',
    description: 'LangChain framework discussions',
    logoUrl: 'https://github.com/langchain-ai.png',
    tier: 2,
    enabled: false, // Migrated to LangChain Forum (discuss.langchain.com)
    repoRef: 'langchain-ai/langchain',
  },
  {
    id: 'github-llama-cpp',
    name: 'llama.cpp',
    sourceType: 'github',
    category: 'ai',
    description: 'LLM inference in C/C++ discussions',
    logoUrl: 'https://github.com/ggml-org.png',
    tier: 1,
    enabled: true,
    repoRef: 'ggml-org/llama.cpp',
  },
  {
    id: 'github-vllm',
    name: 'vLLM',
    sourceType: 'github',
    category: 'ai',
    description: 'High-throughput LLM serving engine discussions',
    logoUrl: 'https://github.com/vllm-project.png',
    tier: 2,
    enabled: false, // Discussions migrated away (March 2025)
    repoRef: 'vllm-project/vllm',
  },
  {
    id: 'github-mlflow',
    name: 'MLflow',
    sourceType: 'github',
    category: 'ai',
    description: 'ML lifecycle platform discussions',
    logoUrl: 'https://github.com/mlflow.png',
    tier: 2,
    enabled: true,
    repoRef: 'mlflow/mlflow',
  },
  {
    id: 'github-jax',
    name: 'JAX',
    sourceType: 'github',
    category: 'ai',
    description: 'Google JAX numerical computing discussions',
    logoUrl: 'https://github.com/jax-ml.png',
    tier: 1,
    enabled: true,
    repoRef: 'jax-ml/jax',
  },
  {
    id: 'github-ollama',
    name: 'Ollama',
    sourceType: 'github',
    category: 'ai',
    description: 'Local LLM runner discussions',
    logoUrl: 'https://github.com/ollama.png',
    tier: 1,
    enabled: true,
    repoRef: 'ollama/ollama',
  },
  {
    id: 'github-open-webui',
    name: 'Open WebUI',
    sourceType: 'github',
    category: 'ai',
    description: 'Open-source LLM web interface discussions',
    logoUrl: 'https://github.com/open-webui.png',
    tier: 2,
    enabled: true,
    repoRef: 'open-webui/open-webui',
  },
  // GitHub Discussions — Open Source
  {
    id: 'github-rust-rfcs',
    name: 'Rust RFCs',
    sourceType: 'github',
    category: 'oss',
    description: 'Rust language RFCs and design discussions',
    logoUrl: 'https://github.com/rust-lang.png',
    tier: 1,
    enabled: false, // No GitHub Discussions — uses PRs + Zulip for RFC discussion
    repoRef: 'rust-lang/rfcs',
  },
  {
    id: 'github-nextjs',
    name: 'Next.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Next.js framework discussions',
    logoUrl: 'https://github.com/vercel.png',
    tier: 1,
    enabled: true,
    repoRef: 'vercel/next.js',
  },
  {
    id: 'github-nodejs',
    name: 'Node.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Node.js runtime discussions',
    logoUrl: 'https://github.com/nodejs.png',
    tier: 2,
    enabled: false, // No GitHub Discussions — uses nodejs/help and Discourse
    repoRef: 'nodejs/node',
  },
  {
    id: 'github-godot-proposals',
    name: 'Godot Proposals',
    sourceType: 'github',
    category: 'oss',
    description: 'Godot engine feature proposals and discussions',
    logoUrl: 'https://github.com/godotengine.png',
    tier: 2,
    enabled: true,
    repoRef: 'godotengine/godot-proposals',
  },
  {
    id: 'github-deno',
    name: 'Deno',
    sourceType: 'github',
    category: 'oss',
    description: 'Deno runtime discussions and proposals',
    logoUrl: 'https://github.com/denoland.png',
    tier: 1,
    enabled: true,
    repoRef: 'denoland/deno',
  },
  {
    id: 'github-bun',
    name: 'Bun',
    sourceType: 'github',
    category: 'oss',
    description: 'Bun JavaScript runtime discussions',
    logoUrl: 'https://github.com/oven-sh.png',
    tier: 1,
    enabled: true,
    repoRef: 'oven-sh/bun',
  },
  {
    id: 'github-vue',
    name: 'Vue.js',
    sourceType: 'github',
    category: 'oss',
    description: 'Vue.js framework discussions and RFCs',
    logoUrl: 'https://github.com/vuejs.png',
    tier: 1,
    enabled: true,
    repoRef: 'vuejs/core',
  },
  {
    id: 'github-svelte',
    name: 'Svelte',
    sourceType: 'github',
    category: 'oss',
    description: 'Svelte framework discussions',
    logoUrl: 'https://github.com/sveltejs.png',
    tier: 2,
    enabled: true,
    repoRef: 'sveltejs/svelte',
  },
  {
    id: 'github-tauri',
    name: 'Tauri',
    sourceType: 'github',
    category: 'oss',
    description: 'Tauri desktop app framework discussions',
    logoUrl: 'https://github.com/tauri-apps.png',
    tier: 2,
    enabled: true,
    repoRef: 'tauri-apps/tauri',
  },
  {
    id: 'github-leptos',
    name: 'Leptos',
    sourceType: 'github',
    category: 'oss',
    description: 'Leptos Rust web framework discussions',
    logoUrl: 'https://github.com/leptos-rs.png',
    tier: 3,
    enabled: true,
    repoRef: 'leptos-rs/leptos',
  },
  {
    id: 'github-homebrew',
    name: 'Homebrew',
    sourceType: 'github',
    category: 'oss',
    description: 'Homebrew package manager discussions',
    logoUrl: 'https://github.com/Homebrew.png',
    tier: 2,
    enabled: true,
    repoRef: 'Homebrew/discussions',
  },
  {
    id: 'github-astro-roadmap',
    name: 'Astro',
    sourceType: 'github',
    category: 'oss',
    description: 'Astro web framework roadmap and feature discussions',
    logoUrl: 'https://github.com/withastro.png',
    tier: 1,
    enabled: true,
    repoRef: 'withastro/roadmap',
  },
  {
    id: 'github-ruff',
    name: 'Ruff',
    sourceType: 'github',
    category: 'oss',
    description: 'Ruff Python linter and formatter discussions',
    logoUrl: 'https://github.com/astral-sh.png',
    tier: 1,
    enabled: true,
    repoRef: 'astral-sh/ruff',
  },
  {
    id: 'github-typescript-go',
    name: 'TypeScript Native',
    sourceType: 'github',
    category: 'oss',
    description: 'TypeScript native port (Go) discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 1,
    enabled: true,
    repoRef: 'microsoft/typescript-go',
  },
  {
    id: 'github-golang',
    name: 'Go',
    sourceType: 'github',
    category: 'oss',
    description: 'Go programming language discussions',
    logoUrl: 'https://github.com/golang.png',
    tier: 2,
    enabled: true,
    repoRef: 'golang/go',
  },
  {
    id: 'github-vscode',
    name: 'VS Code',
    sourceType: 'github',
    category: 'oss',
    description: 'Visual Studio Code discussions',
    logoUrl: 'https://github.com/microsoft.png',
    tier: 2,
    enabled: true,
    repoRef: 'microsoft/vscode-discussions',
  },
  {
    id: 'github-oxc',
    name: 'OXC',
    sourceType: 'github',
    category: 'oss',
    description: 'OXC JavaScript toolchain discussions',
    logoUrl: 'https://github.com/oxc-project.png',
    tier: 2,
    enabled: true,
    repoRef: 'oxc-project/oxc',
  },
  {
    id: 'github-gleam',
    name: 'Gleam',
    sourceType: 'github',
    category: 'oss',
    description: 'Gleam programming language discussions',
    logoUrl: 'https://github.com/gleam-lang.png',
    tier: 3,
    enabled: true,
    repoRef: 'gleam-lang/gleam',
  },
  {
    id: 'github-angular',
    name: 'Angular',
    sourceType: 'github',
    category: 'oss',
    description: 'Angular framework discussions',
    logoUrl: 'https://github.com/angular.png',
    tier: 1,
    enabled: true,
    repoRef: 'angular/angular',
  },
  {
    id: 'github-nuxt',
    name: 'Nuxt',
    sourceType: 'github',
    category: 'oss',
    description: 'Nuxt Vue framework discussions',
    logoUrl: 'https://github.com/nuxt.png',
    tier: 1,
    enabled: true,
    repoRef: 'nuxt/nuxt',
  },
  {
    id: 'github-tailwindcss',
    name: 'Tailwind CSS',
    sourceType: 'github',
    category: 'oss',
    description: 'Tailwind CSS utility framework discussions',
    logoUrl: 'https://github.com/tailwindlabs.png',
    tier: 1,
    enabled: true,
    repoRef: 'tailwindlabs/tailwindcss',
  },
  {
    id: 'github-remix',
    name: 'Remix',
    sourceType: 'github',
    category: 'oss',
    description: 'Remix full-stack web framework discussions',
    logoUrl: 'https://github.com/remix-run.png',
    tier: 2,
    enabled: true,
    repoRef: 'remix-run/remix',
  },
  {
    id: 'github-turbo',
    name: 'Turborepo',
    sourceType: 'github',
    category: 'oss',
    description: 'Turborepo monorepo build system discussions',
    logoUrl: 'https://github.com/vercel.png',
    tier: 2,
    enabled: true,
    repoRef: 'vercel/turbo',
  },
  {
    id: 'github-pnpm',
    name: 'pnpm',
    sourceType: 'github',
    category: 'oss',
    description: 'pnpm package manager discussions',
    logoUrl: 'https://github.com/pnpm.png',
    tier: 2,
    enabled: true,
    repoRef: 'pnpm/pnpm',
  },
  {
    id: 'github-shadcn-ui',
    name: 'shadcn/ui',
    sourceType: 'github',
    category: 'oss',
    description: 'shadcn/ui component library discussions',
    logoUrl: 'https://github.com/shadcn-ui.png',
    tier: 2,
    enabled: true,
    repoRef: 'shadcn-ui/ui',
  },
  {
    id: 'github-biome',
    name: 'Biome',
    sourceType: 'github',
    category: 'oss',
    description: 'Biome JS/TS toolchain discussions',
    logoUrl: 'https://github.com/biomejs.png',
    tier: 2,
    enabled: true,
    repoRef: 'biomejs/biome',
  },
  {
    id: 'github-opentofu',
    name: 'OpenTofu',
    sourceType: 'github',
    category: 'oss',
    description: 'OpenTofu infrastructure-as-code discussions',
    logoUrl: 'https://github.com/opentofu.png',
    tier: 2,
    enabled: true,
    repoRef: 'opentofu/opentofu',
  },
  {
    id: 'github-grafana',
    name: 'Grafana',
    sourceType: 'github',
    category: 'oss',
    description: 'Grafana observability platform discussions',
    logoUrl: 'https://github.com/grafana.png',
    tier: 1,
    enabled: true,
    repoRef: 'grafana/grafana',
  },
  {
    id: 'github-prometheus',
    name: 'Prometheus',
    sourceType: 'github',
    category: 'oss',
    description: 'Prometheus monitoring system discussions',
    logoUrl: 'https://github.com/prometheus.png',
    tier: 1,
    enabled: true,
    repoRef: 'prometheus/prometheus',
  },
  {
    id: 'github-tokio',
    name: 'Tokio',
    sourceType: 'github',
    category: 'oss',
    description: 'Tokio Rust async runtime discussions',
    logoUrl: 'https://github.com/tokio-rs.png',
    tier: 2,
    enabled: true,
    repoRef: 'tokio-rs/tokio',
  },
  {
    id: 'github-typst',
    name: 'Typst',
    sourceType: 'github',
    category: 'oss',
    description: 'Typst typesetting system discussions',
    logoUrl: 'https://github.com/typst.png',
    tier: 3,
    enabled: true,
    repoRef: 'typst/typst',
  },
  {
    id: 'github-deno-fresh',
    name: 'Fresh',
    sourceType: 'github',
    category: 'oss',
    description: 'Fresh web framework for Deno discussions',
    logoUrl: 'https://github.com/denoland.png',
    tier: 3,
    enabled: true,
    repoRef: 'denoland/fresh',
  },
  {
    id: 'github-zed',
    name: 'Zed Editor',
    sourceType: 'github',
    category: 'oss',
    description: 'Zed code editor discussions',
    logoUrl: 'https://github.com/zed-industries.png',
    tier: 2,
    enabled: true,
    repoRef: 'zed-industries/zed',
  },
  // Snapshot Governance Spaces
  {
    id: 'snapshot-aave',
    name: 'Aave (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Aave governance proposals and voting',
    logoUrl: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'aave.eth',
  },
  {
    id: 'snapshot-ens',
    name: 'ENS (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'ENS DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/ethereum-name-service-ens-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'ens.eth',
  },
  {
    id: 'snapshot-arbitrum',
    name: 'Arbitrum (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Arbitrum DAO Snapshot voting',
    logoUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'arbitrumfoundation.eth',
  },
  {
    id: 'snapshot-uniswap',
    name: 'Uniswap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Uniswap governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'uniswapgovernance.eth',
  },
  {
    id: 'snapshot-optimism',
    name: 'Optimism (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Optimism Collective governance voting',
    logoUrl: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'opcollective.eth',
  },
  {
    id: 'snapshot-safe',
    name: 'Safe (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Safe DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/safe-safe-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'safe.eth',
  },
  {
    id: 'snapshot-gitcoin',
    name: 'Gitcoin (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Gitcoin DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/gitcoin-gtc-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'gitcoindao.eth',
  },
  {
    id: 'snapshot-lido',
    name: 'Lido (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Lido DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    tier: 1,
    enabled: true,
    snapshotSpace: 'lido-snapshot.eth',
  },
  {
    id: 'snapshot-balancer',
    name: 'Balancer (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Balancer DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/balancer-bal-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'balancer.eth',
  },
  {
    id: 'snapshot-curve',
    name: 'Curve (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Curve Finance governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'curve.eth',
  },
  {
    id: 'snapshot-compound',
    name: 'Compound (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Compound governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'comp-vote.eth',
  },
  {
    id: 'snapshot-sushiswap',
    name: 'SushiSwap (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'SushiSwap DAO governance proposals',
    logoUrl: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'sushigov.eth',
  },
  {
    id: 'snapshot-gnosis',
    name: 'Gnosis (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'GnosisDAO governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/662/small/logo_square_simple_300px.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'gnosisdao.eth',
  },
  {
    id: 'snapshot-dydx',
    name: 'dYdX (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'dYdX governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/17500/small/dydx.jpg',
    tier: 2,
    enabled: true,
    snapshotSpace: 'dydxgov.eth',
  },
  {
    id: 'snapshot-frax',
    name: 'Frax Finance (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Frax Finance governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/13423/small/frax.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'frax.eth',
  },
  {
    id: 'snapshot-hop',
    name: 'Hop Protocol (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Hop Protocol governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/25445/small/hop.png',
    tier: 3,
    enabled: true,
    snapshotSpace: 'hop.eth',
  },
  {
    id: 'snapshot-rocketpool',
    name: 'Rocket Pool (Snapshot)',
    sourceType: 'snapshot',
    category: 'crypto',
    description: 'Rocket Pool DAO governance proposals',
    logoUrl: 'https://assets.coingecko.com/coins/images/2090/small/rocket_pool.png',
    tier: 2,
    enabled: true,
    snapshotSpace: 'rocketpool-dao.eth',
  },
  // Future sources (disabled for now)
  // {
  //   id: 'hackernews',
  //   name: 'Hacker News',
  //   sourceType: 'hackernews',
  //   category: 'cross',
  //   description: 'Tech news and discussions',
  //   logoUrl: 'https://news.ycombinator.com/favicon.ico',
  //   tier: 2,
  //   enabled: false,
  // },
];

export function getEnabledExternalSources(): ExternalSource[] {
  return EXTERNAL_SOURCES.filter(s => s.enabled);
}

export function getExternalSourcesByCategory(category: 'ai' | 'oss' | 'cross'): ExternalSource[] {
  return EXTERNAL_SOURCES.filter(s => s.category === category && s.enabled);
}
