/**
 * Forum directory organized by three verticals: Crypto, AI, Open Source
 */

export interface ForumPreset {
  name: string;
  url: string;
  categoryId?: number;
  description?: string;
  token?: string;
  logoUrl?: string;
  tier: 1 | 2 | 3;
  sourceType?: 'discourse' | 'ea-forum' | 'lesswrong' | 'github' | 'snapshot' | 'hackernews' | 'lobsters';
  sourceId?: string;  // Maps to EXTERNAL_SOURCES[].id for non-Discourse sources
}

export interface ForumCategory {
  id: string;
  name: string;
  description: string;
  forums: ForumPreset[];
}

export const FORUM_CATEGORIES: ForumCategory[] = [
  {
    id: 'crypto',
    name: 'Crypto',
    description: 'Blockchain protocols, DeFi, DAOs, and governance',
    forums: [
      // L2 Protocols
      {
        name: 'Arbitrum',
        url: 'https://forum.arbitrum.foundation/',
        description: 'Leading Ethereum L2 with full DAO governance',
        token: 'ARB',
        logoUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
        tier: 1,
      },
      {
        name: 'Optimism',
        url: 'https://gov.optimism.io/',
        description: 'Bicameral governance with Token House + Citizens House',
        token: 'OP',
        logoUrl: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png',
        tier: 1,
      },
      {
        name: 'zkSync Era',
        url: 'https://forum.zknation.io/',
        description: 'ZK Nation governance with Token Assembly and Security Council',
        token: 'ZK',
        logoUrl: 'https://cryptologos.cc/logos/zksync-zk-logo.png',
        tier: 1,
      },
      {
        name: 'Polygon',
        url: 'https://forum.polygon.technology/',
        description: 'PIPs governance with Protocol Council',
        token: 'POL',
        logoUrl: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
        tier: 1,
      },
      {
        name: 'Starknet',
        url: 'https://community.starknet.io/',
        description: 'Builders Council + Token Holders governance',
        token: 'STRK',
        logoUrl: 'https://cryptologos.cc/logos/starknet-token-strk-logo.png',
        tier: 1,
      },
      {
        name: 'Mantle',
        url: 'https://forum.mantle.xyz/',
        description: 'L2 with large treasury and Snapshot voting',
        token: 'MNT',
        logoUrl: 'https://assets.coingecko.com/coins/images/30980/small/token-logo.png',
        tier: 2,
      },
      {
        name: 'Mode Network',
        url: 'https://forum.mode.network/',
        description: 'veToken gauge governance; Superchain member',
        token: 'MODE',
        logoUrl: 'https://assets.coingecko.com/coins/images/36735/small/mode.jpeg',
        tier: 2,
      },
      {
        name: 'Linea',
        url: 'https://community.linea.build/',
        description: 'Consensys zkEVM L2; ecosystem development',
        token: 'LINEA',
        logoUrl: 'https://assets.coingecko.com/coins/images/36632/small/linea.jpeg',
        tier: 2,
      },
      {
        name: 'Taiko',
        url: 'https://community.taiko.xyz/',
        description: 'Type 1 ZK-EVM Ethereum L2',
        token: 'TAIKO',
        tier: 3,
      },
      // L1 Protocols
      {
        name: 'Ethereum Magicians',
        url: 'https://ethereum-magicians.org/',
        description: 'Fellowship of Ethereum Magicians for EIP discussions',
        token: 'ETH',
        logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
        tier: 1,
      },
      {
        name: 'Ethereum Research',
        url: 'https://ethresear.ch/',
        description: 'Technical Ethereum research; protocol funding discussions',
        token: 'ETH',
        logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
        tier: 1,
      },
      {
        name: 'Cosmos Hub',
        url: 'https://forum.cosmos.network/',
        description: 'On-chain governance proposals and community pool',
        token: 'ATOM',
        logoUrl: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png',
        tier: 1,
      },
      {
        name: 'Near Protocol',
        url: 'https://gov.near.org/',
        description: 'NEAR Digital Collective governance; House of Stake',
        token: 'NEAR',
        logoUrl: 'https://assets.coingecko.com/coins/images/10365/small/near.jpg',
        tier: 1,
      },
      {
        name: 'Celestia',
        url: 'https://forum.celestia.org/',
        description: 'CIP discussions with rough consensus model',
        token: 'TIA',
        logoUrl: 'https://assets.coingecko.com/coins/images/31967/small/tia.jpg',
        tier: 1,
      },
      {
        name: 'Aptos',
        url: 'https://forum.aptosfoundation.org/',
        description: 'AIPs governance with active voting participation',
        token: 'APT',
        logoUrl: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png',
        tier: 2,
      },
      {
        name: 'BNB Chain',
        url: 'https://forum.bnbchain.org/',
        description: 'Build N Build forum with Tally on-chain votes',
        token: 'BNB',
        logoUrl: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
        tier: 2,
      },
      {
        name: 'Fantom/Sonic',
        url: 'https://forum.fantom.network/',
        description: 'Migrating to Sonic network',
        token: 'FTM',
        logoUrl: 'https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png',
        tier: 2,
      },
      {
        name: 'Polkadot',
        url: 'https://forum.polkadot.network/',
        description: 'OpenGov referenda and parachain discussions',
        token: 'DOT',
        logoUrl: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png',
        tier: 1,
      },
      {
        name: 'Cardano',
        url: 'https://forum.cardano.org/',
        description: 'CIPs and Catalyst project governance',
        token: 'ADA',
        logoUrl: 'https://assets.coingecko.com/coins/images/975/small/cardano.png',
        tier: 1,
      },
      {
        name: 'Solana',
        url: 'https://forum.solana.com/',
        description: 'SIMD proposals and validator policies',
        token: 'SOL',
        logoUrl: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
        tier: 1,
      },
      {
        name: 'Tezos Agora',
        url: 'https://forum.tezosagora.org/',
        description: 'Protocol amendments and governance',
        token: 'XTZ',
        logoUrl: 'https://assets.coingecko.com/coins/images/976/small/Tezos-logo.png',
        tier: 2,
      },
      {
        name: 'Sui',
        url: 'https://forums.sui.io/',
        description: 'Developer forum; governance evolving',
        token: 'SUI',
        logoUrl: 'https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg',
        tier: 3,
      },
      {
        name: 'Tron',
        url: 'https://forum.trondao.org/',
        description: 'Super Representative governance',
        token: 'TRX',
        logoUrl: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png',
        tier: 3,
      },
      {
        name: 'Avalanche',
        url: 'https://forum.avax.network/',
        description: 'Subnet architecture with active validator governance',
        token: 'AVAX',
        tier: 1,
      },
      {
        name: 'Berachain',
        url: 'https://forum.berachain.com/',
        description: 'EVM L1 with Proof of Liquidity consensus',
        token: 'BERA',
        tier: 2,
      },
      {
        name: 'Stacks',
        url: 'https://forum.stacks.org/',
        description: 'Bitcoin L2 with SIP governance',
        token: 'STX',
        tier: 2,
      },
      {
        name: 'Algorand',
        url: 'https://forum.algorand.co/',
        description: 'Pure proof-of-stake L1 governance',
        token: 'ALGO',
        tier: 2,
      },
      {
        name: 'Internet Computer',
        url: 'https://forum.dfinity.org/',
        description: 'NNS governance and canister smart contracts',
        token: 'ICP',
        tier: 2,
      },
      {
        name: 'Mina Protocol',
        url: 'https://forums.minaprotocol.com/',
        description: 'Lightweight ZK blockchain governance',
        token: 'MINA',
        tier: 3,
      },
      {
        name: 'Flare Network',
        url: 'https://forum.flare.network/',
        description: 'Data oracle network for cross-chain',
        token: 'FLR',
        tier: 3,
      },
      // Major DAOs
      {
        name: 'ENS',
        url: 'https://discuss.ens.domains/',
        description: 'Ethereum Name Service governance',
        token: 'ENS',
        logoUrl: 'https://assets.coingecko.com/coins/images/19785/small/acatxTm8_400x400.jpg',
        tier: 1,
      },
      {
        name: 'Gitcoin',
        url: 'https://gov.gitcoin.co/',
        description: 'Public goods funding governance',
        token: 'GTC',
        logoUrl: 'https://assets.coingecko.com/coins/images/15810/small/gitcoin.png',
        tier: 1,
      },
      {
        name: 'ApeCoin DAO',
        url: 'https://forum.apecoin.com/',
        description: 'BAYC ecosystem governance',
        token: 'APE',
        logoUrl: 'https://assets.coingecko.com/coins/images/24383/small/apecoin.jpg',
        tier: 2,
      },
      {
        name: 'Decentraland',
        url: 'https://forum.decentraland.org/',
        description: 'Virtual world governance',
        token: 'MANA',
        logoUrl: 'https://assets.coingecko.com/coins/images/878/small/decentraland-mana.png',
        tier: 2,
      },
      {
        name: 'Treasure DAO',
        url: 'https://forum.treasure.lol/',
        description: 'Gaming ecosystem on Arbitrum',
        token: 'MAGIC',
        logoUrl: 'https://assets.coingecko.com/coins/images/18623/small/magic.png',
        tier: 3,
      },
      {
        name: 'Octant',
        url: 'https://discuss.octant.app/',
        description: 'Golem Foundation public goods funding',
        tier: 3,
      },
      // Infrastructure
      {
        name: 'The Graph',
        url: 'https://forum.thegraph.com/',
        description: 'Indexing protocol with GIP governance',
        token: 'GRT',
        logoUrl: 'https://assets.coingecko.com/coins/images/13397/small/Graph_Token.png',
        tier: 2,
      },
      {
        name: 'SafeDAO',
        url: 'https://forum.safe.global/',
        description: 'Multisig infrastructure governance',
        token: 'SAFE',
        logoUrl: 'https://assets.coingecko.com/coins/images/28032/small/safe.png',
        tier: 2,
      },
      {
        name: 'Pocket Network',
        url: 'https://forum.pokt.network/',
        description: 'Decentralized RPC with PoP governance',
        token: 'POKT',
        logoUrl: 'https://assets.coingecko.com/coins/images/22506/small/pokt.png',
        tier: 2,
      },
      {
        name: 'Wormhole',
        url: 'https://forum.wormhole.com/',
        description: 'Cross-chain messaging with MultiGov',
        token: 'W',
        logoUrl: 'https://assets.coingecko.com/coins/images/35087/small/wormhole.jpg',
        tier: 2,
      },
      {
        name: 'Radworks',
        url: 'https://community.radworks.org/',
        description: 'Decentralized code collaboration',
        token: 'RAD',
        logoUrl: 'https://assets.coingecko.com/coins/images/14013/small/radicle.png',
        tier: 2,
      },
      {
        name: 'Livepeer',
        url: 'https://forum.livepeer.org/',
        description: 'Decentralized video transcoding',
        token: 'LPT',
        logoUrl: 'https://assets.coingecko.com/coins/images/7137/small/logo-circle-green.png',
        tier: 2,
      },
      {
        name: 'Hop Protocol',
        url: 'https://forum.hop.exchange/',
        description: 'Bridge protocol with HIP proposals',
        token: 'HOP',
        logoUrl: 'https://assets.coingecko.com/coins/images/25445/small/hop.png',
        tier: 2,
      },
      {
        name: 'UMA Protocol',
        url: 'https://discourse.uma.xyz/',
        description: 'Optimistic oracle with UMIP governance',
        token: 'UMA',
        logoUrl: 'https://assets.coingecko.com/coins/images/10951/small/UMA.png',
        tier: 2,
      },
      {
        name: 'Index Coop',
        url: 'https://gov.indexcoop.com/',
        description: 'Structured DeFi products',
        token: 'INDEX',
        logoUrl: 'https://assets.coingecko.com/coins/images/12729/small/index.png',
        tier: 2,
      },
      {
        name: 'CoW Protocol',
        url: 'https://forum.cow.fi/',
        description: 'MEV protection and batch auctions; Grants Council',
        token: 'COW',
        logoUrl: 'https://assets.coingecko.com/coins/images/24384/small/cow.png',
        tier: 1,
      },
      {
        name: 'Across Protocol',
        url: 'https://forum.across.to/',
        description: 'Cross-chain bridge powered by UMA',
        token: 'ACX',
        logoUrl: 'https://assets.coingecko.com/coins/images/28161/small/across.png',
        tier: 2,
      },
      {
        name: 'Pyth Network',
        url: 'https://forum.pyth.network/',
        description: 'Cross-chain oracle network for DeFi',
        token: 'PYTH',
        tier: 2,
      },
      {
        name: 'Everclear',
        url: 'https://forum.connext.network/',
        description: 'Cross-chain clearing layer (formerly Connext)',
        token: 'NEXT',
        tier: 3,
      },

      // Lending
      {
        name: 'Aave',
        url: 'https://governance.aave.com/',
        categoryId: 4,
        description: 'Largest DeFi lending protocol',
        token: 'AAVE',
        logoUrl: 'https://cryptologos.cc/logos/aave-aave-logo.png',
        tier: 1,
      },
      {
        name: 'Compound',
        url: 'https://www.comp.xyz/',
        description: 'Pioneer lending protocol with Governor Bravo',
        token: 'COMP',
        logoUrl: 'https://assets.coingecko.com/coins/images/10775/small/COMP.png',
        tier: 1,
      },
      {
        name: 'Sky (MakerDAO)',
        url: 'https://forum.sky.money/',
        description: 'Rebranded from Maker; Endgame transition',
        token: 'MKR',
        logoUrl: 'https://assets.coingecko.com/coins/images/1364/small/Mark_Maker.png',
        tier: 1,
      },
      // MakerDAO Legacy removed - migrated to Sky
      {
        name: 'Morpho',
        url: 'https://forum.morpho.org/',
        description: 'Optimized lending layer',
        token: 'MORPHO',
        logoUrl: 'https://assets.coingecko.com/coins/images/29837/small/morpho.png',
        tier: 2,
      },
      {
        name: 'Euler Finance',
        url: 'https://forum.euler.finance/',
        description: 'Modular lending protocol',
        token: 'EUL',
        logoUrl: 'https://assets.coingecko.com/coins/images/26149/small/euler.png',
        tier: 2,
      },
      {
        name: 'Goldfinch',
        url: 'https://gov.goldfinch.finance/',
        description: 'Credit protocol for real-world lending',
        token: 'GFI',
        logoUrl: 'https://assets.coingecko.com/coins/images/19081/small/goldfinch.png',
        tier: 3,
      },
      {
        name: 'Inverse Finance',
        url: 'https://forum.inverse.finance/',
        description: 'Fixed-rate lending',
        token: 'INV',
        logoUrl: 'https://assets.coingecko.com/coins/images/14205/small/inverse.png',
        tier: 3,
      },
      {
        name: 'Venus Protocol',
        url: 'https://community.venus.io/',
        description: 'BNB Chain money market',
        token: 'XVS',
        logoUrl: 'https://assets.coingecko.com/coins/images/12677/small/venus.png',
        tier: 2,
      },
      {
        name: 'Maple Finance',
        url: 'https://community.maple.finance/',
        description: 'Institutional lending',
        token: 'MPL',
        logoUrl: 'https://assets.coingecko.com/coins/images/14097/small/maple.png',
        tier: 3,
      },
      {
        name: 'Radiant Capital',
        url: 'https://community.radiant.capital/',
        description: 'Omnichain lending',
        token: 'RDNT',
        logoUrl: 'https://assets.coingecko.com/coins/images/26536/small/radiant.png',
        tier: 3,
      },
      // DEX (Uniswap governance covered by Snapshot source in externalSources.ts)
      {
        name: 'Curve Finance',
        url: 'https://gov.curve.finance/',
        description: 'Stablecoin DEX with veCRV gauge',
        token: 'CRV',
        logoUrl: 'https://assets.coingecko.com/coins/images/12124/small/Curve.png',
        tier: 1,
      },
      {
        name: 'Balancer',
        url: 'https://forum.balancer.fi/',
        description: 'Programmable liquidity protocol',
        token: 'BAL',
        logoUrl: 'https://assets.coingecko.com/coins/images/11683/small/Balancer.png',
        tier: 1,
      },
      {
        name: 'PancakeSwap',
        url: 'https://forum.pancakeswap.finance/',
        description: 'Multi-chain DEX',
        token: 'CAKE',
        logoUrl: 'https://assets.coingecko.com/coins/images/12632/small/pancakeswap.png',
        tier: 2,
      },
      {
        name: 'dYdX',
        url: 'https://dydx.forum/',
        description: 'Decentralized perpetuals exchange',
        token: 'DYDX',
        logoUrl: 'https://assets.coingecko.com/coins/images/17500/small/dydx.jpg',
        tier: 1,
      },
      {
        name: 'Bancor',
        url: 'https://gov.bancor.network/',
        description: 'Single-sided liquidity',
        token: 'BNT',
        logoUrl: 'https://assets.coingecko.com/coins/images/736/small/bancor-bnt.png',
        tier: 2,
      },
      {
        name: '1inch',
        url: 'https://gov.1inch.io/',
        description: 'DEX aggregator governance',
        token: '1INCH',
        logoUrl: 'https://assets.coingecko.com/coins/images/13469/small/1inch.png',
        tier: 2,
      },
      {
        name: 'Osmosis',
        url: 'https://forum.osmosis.zone/',
        description: 'Cosmos ecosystem DEX with superfluid staking',
        token: 'OSMO',
        tier: 2,
      },
      // Staking
      {
        name: 'Lido Finance',
        url: 'https://research.lido.fi/',
        description: 'Liquid staking governance',
        token: 'LDO',
        logoUrl: 'https://assets.coingecko.com/coins/images/13573/small/lido.png',
        tier: 1,
      },
      {
        name: 'EigenLayer',
        url: 'https://forum.eigenlayer.xyz/',
        description: 'Restaking protocol governance',
        token: 'EIGEN',
        logoUrl: 'https://assets.coingecko.com/coins/images/37441/small/eigenlayer.jpeg',
        tier: 1,
      },
      {
        name: 'Rocket Pool',
        url: 'https://dao.rocketpool.net/',
        description: 'Decentralized ETH staking',
        token: 'RPL',
        logoUrl: 'https://assets.coingecko.com/coins/images/2090/small/rocket_pool.png',
        tier: 2,
      },
      {
        name: 'Jito',
        url: 'https://forum.jito.network/',
        description: 'Solana MEV and liquid staking',
        token: 'JTO',
        tier: 2,
      },
      // Other DeFi
      {
        name: 'Yearn Finance',
        url: 'https://gov.yearn.fi/',
        description: 'Yield aggregator governance',
        token: 'YFI',
        logoUrl: 'https://assets.coingecko.com/coins/images/11849/small/yearn.jpg',
        tier: 1,
      },
      {
        name: 'Frax Finance',
        url: 'https://gov.frax.finance/',
        description: 'Fractional-algorithmic stablecoin',
        token: 'FXS',
        logoUrl: 'https://assets.coingecko.com/coins/images/13423/small/frax.png',
        tier: 2,
      },
      {
        name: 'Centrifuge',
        url: 'https://gov.centrifuge.io/',
        description: 'Real-world asset financing',
        token: 'CFG',
        logoUrl: 'https://assets.coingecko.com/coins/images/16441/small/centrifuge.png',
        tier: 2,
      },
      {
        name: 'Angle Protocol',
        url: 'https://gov.angle.money/',
        description: 'Decentralized stablecoin',
        token: 'ANGLE',
        logoUrl: 'https://assets.coingecko.com/coins/images/19060/small/angle.png',
        tier: 2,
      },
      {
        name: 'Reserve Protocol',
        url: 'https://forum.reserve.org/',
        description: 'Asset-backed stablecoins',
        token: 'RSR',
        logoUrl: 'https://assets.coingecko.com/coins/images/8365/small/reserve.png',
        tier: 2,
      },
      {
        name: 'Ethena',
        url: 'https://gov.ethenafoundation.com/',
        description: 'Synthetic dollar protocol (USDe)',
        token: 'ENA',
        tier: 2,
      },

      // Privacy
      {
        name: 'Zcash',
        url: 'https://forum.zcashcommunity.com/',
        description: 'Privacy coin governance; ZIP 1014 dev fund',
        token: 'ZEC',
        logoUrl: 'https://assets.coingecko.com/coins/images/486/small/zcash.png',
        tier: 2,
      },
      {
        name: 'Secret Network',
        url: 'https://forum.scrt.network/',
        description: 'Privacy-preserving smart contracts',
        token: 'SCRT',
        logoUrl: 'https://assets.coingecko.com/coins/images/11871/small/secret.png',
        tier: 2,
      },
      {
        name: 'Aztec',
        url: 'https://forum.aztec.network/',
        description: 'ZK privacy layer for Ethereum',
        logoUrl: 'https://assets.coingecko.com/coins/images/26116/small/aztec.jpeg',
        tier: 2,
      },
      // AI-Crypto
      {
        name: 'Numerai',
        url: 'https://forum.numer.ai/',
        description: 'AI hedge fund and data scientist tournaments',
        token: 'NMR',
        logoUrl: 'https://assets.coingecko.com/coins/images/752/small/numeraire.png',
        tier: 2,
      },
      {
        name: 'Phala Network',
        url: 'https://forum.phala.network/',
        description: 'Confidential cloud computing; TEE-based AI',
        token: 'PHA',
        logoUrl: 'https://assets.coingecko.com/coins/images/12451/small/phala.png',
        tier: 3,
      },
      // GitHub Discussions — Crypto
      {
        name: 'Foundry',
        url: 'https://github.com/foundry-rs/foundry/discussions',
        description: 'Foundry toolkit for Ethereum development',
        logoUrl: 'https://github.com/foundry-rs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-foundry',
      },
      {
        name: 'Hardhat',
        url: 'https://github.com/NomicFoundation/hardhat/discussions',
        description: 'Hardhat Ethereum development environment',
        logoUrl: 'https://github.com/NomicFoundation.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-hardhat',
      },
      {
        name: 'Reth',
        url: 'https://github.com/paradigmxyz/reth/discussions',
        description: 'Reth Ethereum execution client discussions',
        logoUrl: 'https://github.com/paradigmxyz.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-reth',
      },
      {
        name: 'Filecoin FIPs',
        url: 'https://github.com/filecoin-project/FIPs/discussions',
        description: 'Filecoin Improvement Proposals discussions',
        logoUrl: 'https://github.com/filecoin-project.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-filecoin-fips',
      },
      {
        name: 'Uniswap Governance',
        url: 'https://gov.uniswap.org/',
        description: 'Uniswap protocol governance (proposals, treasury, fee switch)',
        token: 'UNI',
        logoUrl: 'https://icons.llama.fi/uniswap.jpg',
        tier: 1,
      },
      {
        name: 'GMX',
        url: 'https://gov.gmx.io/',
        description: 'GMX perpetuals DEX governance',
        token: 'GMX',
        logoUrl: 'https://icons.llama.fi/gmx.jpg',
        tier: 1,
      },
      {
        name: 'Monad',
        url: 'https://forum.monad.xyz/',
        description: 'Monad L1 governance and ecosystem discussions',
        token: 'MON',
        logoUrl: 'https://avatars.githubusercontent.com/u/154944731',
        tier: 1,
      },
      {
        name: 'Delving Bitcoin',
        url: 'https://delvingbitcoin.org/',
        description: 'Bitcoin Core research and protocol discussion (bitcoin-dev successor)',
        token: 'BTC',
        logoUrl: 'https://bitcoin.org/img/icons/opengraph.png',
        tier: 1,
      },
      {
        name: 'Kamino Finance',
        url: 'https://gov.kamino.finance/',
        description: 'Solana lending/borrowing protocol governance',
        token: 'KMNO',
        logoUrl: 'https://icons.llama.fi/kamino.jpg',
        tier: 2,
      },
      {
        name: 'Marinade Finance',
        url: 'https://forum.marinade.finance/',
        description: 'Solana liquid staking governance',
        token: 'MNDE',
        logoUrl: 'https://icons.llama.fi/marinade-finance.jpg',
        tier: 2,
      },
      {
        name: 'Renzo',
        url: 'https://gov.renzoprotocol.com/',
        description: 'Renzo restaking and LRT governance',
        token: 'REZ',
        logoUrl: 'https://icons.llama.fi/renzo.jpg',
        tier: 2,
      },
      {
        name: 'Flow',
        url: 'https://forum.onflow.org/',
        description: 'Flow blockchain governance and ecosystem',
        token: 'FLOW',
        logoUrl: 'https://icons.llama.fi/flow.jpg',
        tier: 2,
      },
      {
        name: 'Aurora',
        url: 'https://forum.aurora.dev/',
        description: 'NEAR EVM (Aurora) governance and ecosystem',
        token: 'AURORA',
        logoUrl: 'https://icons.llama.fi/aurora.jpg',
        tier: 3,
      },
      {
        name: 'Story Protocol',
        url: 'https://forum.story.foundation/',
        description: 'Story Protocol IP/governance (SIP proposals, treasury)',
        token: 'IP',
        logoUrl: 'https://avatars.githubusercontent.com/u/154944867',
        tier: 1,
      },
      {
        name: 'Threshold Network',
        url: 'https://forum.threshold.network/',
        description: 'Threshold Network governance (tBTC, threshold cryptography)',
        token: 'T',
        logoUrl: 'https://icons.llama.fi/threshold-network.jpg',
        tier: 2,
      },
      {
        name: 'IoTeX',
        url: 'https://community.iotex.io/',
        description: 'IoTeX DePIN L1 governance and IIPs',
        token: 'IOTX',
        logoUrl: 'https://icons.llama.fi/iotex.jpg',
        tier: 2,
      },
      {
        name: 'Initia',
        url: 'https://forum.initia.xyz/',
        description: 'Initia L1 governance and IBC parameters',
        token: 'INIT',
        logoUrl: 'https://avatars.githubusercontent.com/u/164263486',
        tier: 2,
      },
      {
        name: 'BOB (Build on Bitcoin)',
        url: 'https://forum.gobob.xyz/',
        description: 'BOB DAO governance, Bitcoin L2 hybrid chain',
        token: 'BOB',
        logoUrl: 'https://icons.llama.fi/bob.jpg',
        tier: 2,
      },
      {
        name: 'SKALE',
        url: 'https://forum.skale.network/',
        description: 'SKALE Network governance (SIPs, validator economics)',
        token: 'SKL',
        logoUrl: 'https://icons.llama.fi/skale.jpg',
        tier: 2,
      },
      {
        name: 'Sovryn',
        url: 'https://forum.sovryn.com/',
        description: 'Sovryn governance, Bitcoin-native DeFi',
        token: 'SOV',
        logoUrl: 'https://icons.llama.fi/sovryn.jpg',
        tier: 2,
      },
      {
        name: 'OpenZeppelin Community',
        url: 'https://forum.openzeppelin.com/',
        description: 'Web3 security, Solidity contracts, OpenZeppelin libraries',
        token: 'OZ',
        logoUrl: 'https://avatars.githubusercontent.com/u/20820676',
        tier: 2,
      },
      {
        name: 'Hacker News · Crypto',
        url: 'https://news.ycombinator.com/#crypto',
        description: 'Top HN stories on Ethereum, Bitcoin, rollups, and onchain protocols',
        logoUrl: 'https://news.ycombinator.com/favicon.ico',
        tier: 2,
        sourceType: 'hackernews',
        sourceId: 'hn-crypto',
      },

    ],
  },
  {
    id: 'ai',
    name: 'AI',
    description: 'AI research, ML tools, and developer communities',
    forums: [
      {
        name: 'EA Forum',
        url: 'https://forum.effectivealtruism.org',
        description: 'AI safety, funding, grants, Open Philanthropy discussions',
        logoUrl: 'https://forum.effectivealtruism.org/favicon.ico',
        tier: 1,
        sourceType: 'ea-forum',
      },
      // LessWrong disabled: Vercel bot protection blocks GraphQL API from server-side
      {
        name: 'Hugging Face',
        url: 'https://discuss.huggingface.co/',
        description: 'Open-source ML hub; Transformers, Spaces',
        logoUrl: 'https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo.png',
        tier: 1,
      },
      {
        name: 'PyTorch',
        url: 'https://discuss.pytorch.org/',
        description: 'Official PyTorch community',
        logoUrl: 'https://pytorch.org/assets/images/pytorch-logo.png',
        tier: 1,
      },
      {
        name: 'PyTorch Dev',
        url: 'https://dev-discuss.pytorch.org/',
        description: 'Core PyTorch development governance',
        logoUrl: 'https://pytorch.org/assets/images/pytorch-logo.png',
        tier: 2,
      },
    
      {
        name: 'OpenAI Community',
        url: 'https://community.openai.com/',
        description: 'Primary API developer forum for OpenAI',
        logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/200px-OpenAI_Logo.svg.png',
        tier: 1,
      },
      {
        name: 'LangChain',
        url: 'https://forum.langchain.com/',
        description: 'LLM application development',
        logoUrl: 'https://avatars.githubusercontent.com/u/126733545',
        tier: 2,
      },
      {
        name: 'Google AI',
        url: 'https://discuss.ai.google.dev/',
        description: 'Gemini, TensorFlow, Google AI tools',
        logoUrl: 'https://www.gstatic.com/devrel-devsite/prod/v45f61267e22826169cf5d5f452882f7812c8cfb5f8b103a48c0d88727908b295/developers/images/touchicon-180.png',
        tier: 2,
      },
      {
        name: 'Python',
        url: 'https://discuss.python.org/',
        description: 'CPython development, PEPs, and packaging',
        logoUrl: 'https://www.python.org/static/community_logos/python-logo-generic.svg',
        tier: 1,
      },
      {
        name: 'Scientific Python',
        url: 'https://discuss.scientific-python.org/',
        description: 'NumPy, SciPy, and scientific Python ecosystem',
        tier: 2,
      },
      {
        name: 'OSI Discuss',
        url: 'https://discuss.opensource.org/',
        description: 'Open Source Initiative policy and licensing',
        tier: 2,
      },
      // GitHub Discussions — AI
      {
        name: 'llama.cpp',
        url: 'https://github.com/ggml-org/llama.cpp/discussions',
        description: 'LLM inference in C/C++ discussions',
        logoUrl: 'https://github.com/ggml-org.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-llama-cpp',
      },
      {
        name: 'MLflow',
        url: 'https://github.com/mlflow/mlflow/discussions',
        description: 'ML lifecycle platform discussions',
        logoUrl: 'https://github.com/mlflow.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-mlflow',
      },
      {
        name: 'JAX',
        url: 'https://github.com/jax-ml/jax/discussions',
        description: 'Google JAX numerical computing discussions',
        logoUrl: 'https://github.com/jax-ml.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-jax',
      },
      {
        name: 'Open WebUI',
        url: 'https://github.com/open-webui/open-webui/discussions',
        description: 'Open-source LLM web interface discussions',
        logoUrl: 'https://github.com/open-webui.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-open-webui',
      },
      {
        name: 'Modular (Mojo)',
        url: 'https://forum.modular.com/',
        description: 'Mojo language and MAX engine developer community',
        logoUrl: 'https://avatars.githubusercontent.com/u/72929097',
        tier: 1,
      },
      {
        name: 'Cursor',
        url: 'https://forum.cursor.com/',
        description: 'Cursor AI code editor community',
        logoUrl: 'https://avatars.githubusercontent.com/u/126759922',
        tier: 1,
      },
      {
        name: 'Weights & Biases Community',
        url: 'https://community.wandb.ai/',
        description: 'W&B ML experiment tracking and MLOps discussions',
        logoUrl: 'https://avatars.githubusercontent.com/u/26401354',
        tier: 1,
      },
      {
        name: 'Streamlit',
        url: 'https://discuss.streamlit.io/',
        description: 'Streamlit data app framework community',
        logoUrl: 'https://avatars.githubusercontent.com/u/45109972',
        tier: 1,
      },
      {
        name: 'Plotly / Dash',
        url: 'https://community.plotly.com/',
        description: 'Plotly visualization and Dash app framework community',
        logoUrl: 'https://avatars.githubusercontent.com/u/5997976',
        tier: 2,
      },
      {
        name: 'DVC',
        url: 'https://discuss.dvc.org/',
        description: 'Data Version Control and Iterative MLOps tools community',
        logoUrl: 'https://avatars.githubusercontent.com/u/27135737',
        tier: 2,
      },
      {
        name: 'Apache TVM',
        url: 'https://discuss.tvm.apache.org/',
        description: 'Apache TVM ML compiler and inference engine discussions',
        logoUrl: 'https://avatars.githubusercontent.com/u/17613106',
        tier: 2,
      },
      {
        name: 'Weaviate Community',
        url: 'https://forum.weaviate.io/',
        description: 'Weaviate vector database community (RAG, embeddings, ANN)',
        logoUrl: 'https://avatars.githubusercontent.com/u/37794290',
        tier: 1,
      },
      {
        name: 'Ray / Anyscale',
        url: 'https://discuss.ray.io/',
        description: 'Ray distributed compute, RLlib, Train, Serve (Anyscale)',
        logoUrl: 'https://avatars.githubusercontent.com/u/22125274',
        tier: 1,
      },
      {
        name: 'CrewAI',
        url: 'https://community.crewai.com/',
        description: 'CrewAI multi-agent orchestration framework community',
        logoUrl: 'https://avatars.githubusercontent.com/u/170677839',
        tier: 2,
      },
      {
        name: 'LlamaIndex',
        url: 'https://github.com/run-llama/llama_index/discussions',
        description: 'LlamaIndex RAG framework discussions',
        logoUrl: 'https://github.com/run-llama.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-llamaindex',
      },
      {
        name: 'Hacker News · AI',
        url: 'https://news.ycombinator.com/#ai',
        description: 'Top HN stories on LLMs, AI models, and ML tooling',
        logoUrl: 'https://news.ycombinator.com/favicon.ico',
        tier: 1,
        sourceType: 'hackernews',
        sourceId: 'hn-ai',
      },
      {
        name: 'Lobsters · AI',
        url: 'https://lobste.rs/t/ai',
        description: 'Recent Lobsters discussions tagged AI/ML',
        logoUrl: 'https://lobste.rs/favicon.ico',
        tier: 2,
        sourceType: 'lobsters',
        sourceId: 'lobsters-ai',
      },
      {
        name: 'fast.ai',
        url: 'https://forums.fast.ai/',
        description: 'fast.ai deep-learning course and library community',
        logoUrl: 'https://forums.fast.ai/favicon.ico',
        tier: 2,
      },
      {
        name: 'n8n',
        url: 'https://community.n8n.io/',
        description: 'n8n workflow-automation and AI-agent community',
        logoUrl: 'https://community.n8n.io/favicon.ico',
        tier: 2,
      },

    ],
  },
  {
    id: 'oss',
    name: 'Open Source',
    description: 'Programming languages, frameworks, and infrastructure',
    forums: [
      {
        name: 'Erlang',
        url: 'https://erlangforums.com/',
        description: 'Erlang community forum',
        logoUrl: 'https://erlangforums.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Elm Discourse',
        url: 'https://discourse.elm-lang.org/',
        description: 'Elm Discourse community forum',
        logoUrl: 'https://discourse.elm-lang.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Scala Users',
        url: 'https://users.scala-lang.org/',
        description: 'Scala Users community forum',
        logoUrl: 'https://users.scala-lang.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Scala Contributors',
        url: 'https://contributors.scala-lang.org/',
        description: 'Scala Contributors community forum',
        logoUrl: 'https://contributors.scala-lang.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Go Forum (GoBridge)',
        url: 'https://forum.golangbridge.org/',
        description: 'Go Forum (GoBridge) community forum',
        logoUrl: 'https://forum.golangbridge.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Haxe',
        url: 'https://community.haxe.org/',
        description: 'Haxe community forum',
        logoUrl: 'https://community.haxe.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Rocq Prover',
        url: 'https://discourse.rocq-prover.org/',
        description: 'Rocq Prover community forum',
        logoUrl: 'https://discourse.rocq-prover.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Netdata Community',
        url: 'https://community.netdata.cloud/',
        description: 'Netdata Community community forum',
        logoUrl: 'https://community.netdata.cloud/favicon.ico',
        tier: 2,
      },
      {
        name: 'Temporal',
        url: 'https://community.temporal.io/',
        description: 'Temporal community forum',
        logoUrl: 'https://community.temporal.io/favicon.ico',
        tier: 2,
      },
      {
        name: 'ScyllaDB Community NoSQL',
        url: 'https://forum.scylladb.com/',
        description: 'ScyllaDB Community NoSQL community forum',
        logoUrl: 'https://forum.scylladb.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Percona',
        url: 'https://forums.percona.com/',
        description: 'Percona community forum',
        logoUrl: 'https://forums.percona.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Keycloak',
        url: 'https://forum.keycloak.org/',
        description: 'Keycloak community forum',
        logoUrl: 'https://forum.keycloak.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Camunda',
        url: 'https://forum.camunda.io/',
        description: 'Camunda community forum',
        logoUrl: 'https://forum.camunda.io/favicon.ico',
        tier: 2,
      },
      {
        name: 'SUSE Rancher Community',
        url: 'https://forums.suse.com/',
        description: 'SUSE Rancher Community community forum',
        logoUrl: 'https://forums.suse.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Crossplane',
        url: 'https://github.com/crossplane/crossplane/discussions',
        description: 'Crossplane GitHub Discussions',
        logoUrl: 'https://github.com/crossplane.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-crossplane',
      },
      {
        name: 'Trino',
        url: 'https://github.com/trinodb/trino/discussions',
        description: 'Trino GitHub Discussions',
        logoUrl: 'https://github.com/trinodb.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-trino',
      },
      {
        name: 'Prefect',
        url: 'https://github.com/PrefectHQ/prefect/discussions',
        description: 'Prefect GitHub Discussions',
        logoUrl: 'https://github.com/PrefectHQ.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-prefect',
      },
      {
        name: 'Airbyte',
        url: 'https://github.com/airbytehq/airbyte/discussions',
        description: 'Airbyte GitHub Discussions',
        logoUrl: 'https://github.com/airbytehq.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-airbyte',
      },
      {
        name: 'Dagster',
        url: 'https://github.com/dagster-io/dagster/discussions',
        description: 'Dagster GitHub Discussions',
        logoUrl: 'https://github.com/dagster-io.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-dagster',
      },
      {
        name: 'Linkerd',
        url: 'https://github.com/linkerd/linkerd2/discussions',
        description: 'Linkerd GitHub Discussions',
        logoUrl: 'https://github.com/linkerd.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-linkerd2',
      },
      {
        name: 'Fluent Bit',
        url: 'https://github.com/fluent/fluent-bit/discussions',
        description: 'Fluent Bit GitHub Discussions',
        logoUrl: 'https://github.com/fluent.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-fluent-bit',
      },
      {
        name: 'openSUSE',
        url: 'https://forums.opensuse.org/',
        description: 'openSUSE community forum',
        logoUrl: 'https://forums.opensuse.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Manjaro Linux',
        url: 'https://forum.manjaro.org/',
        description: 'Manjaro Linux community forum',
        logoUrl: 'https://forum.manjaro.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'EndeavourOS',
        url: 'https://forum.endeavouros.com/',
        description: 'EndeavourOS community forum',
        logoUrl: 'https://forum.endeavouros.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Rocky Linux',
        url: 'https://forums.rockylinux.org/',
        description: 'Rocky Linux community forum',
        logoUrl: 'https://forums.rockylinux.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Framework',
        url: 'https://community.frame.work/',
        description: 'Framework community forum',
        logoUrl: 'https://community.frame.work/favicon.ico',
        tier: 2,
      },
      {
        name: 'TrueNAS Community',
        url: 'https://forums.truenas.com/',
        description: 'TrueNAS Community community forum',
        logoUrl: 'https://forums.truenas.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Nextcloud',
        url: 'https://help.nextcloud.com/',
        description: 'Nextcloud community forum',
        logoUrl: 'https://help.nextcloud.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Pi-hole Userspace',
        url: 'https://discourse.pi-hole.net/',
        description: 'Pi-hole Userspace community forum',
        logoUrl: 'https://discourse.pi-hole.net/favicon.ico',
        tier: 2,
      },
      {
        name: 'OpenWrt',
        url: 'https://forum.openwrt.org/',
        description: 'OpenWrt community forum',
        logoUrl: 'https://forum.openwrt.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Grafana Community',
        url: 'https://community.grafana.com/',
        description: 'Grafana Community community forum',
        logoUrl: 'https://community.grafana.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Practical ZFS',
        url: 'https://discourse.practicalzfs.com/',
        description: 'Practical ZFS community forum',
        logoUrl: 'https://discourse.practicalzfs.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Haiku',
        url: 'https://discuss.haiku-os.org/',
        description: 'Haiku community forum',
        logoUrl: 'https://discuss.haiku-os.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Docker Community',
        url: 'https://forums.docker.com/',
        description: 'Docker Community community forum',
        logoUrl: 'https://forums.docker.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Ionic Forum (Ionic / Capacitor / Stencil)',
        url: 'https://forum.ionicframework.com/',
        description: 'Ionic Forum (Ionic / Capacitor / Stencil) community forum',
        logoUrl: 'https://forum.ionicframework.com/favicon.ico',
        tier: 2,
      },
      {
        name: 'Webpack',
        url: 'https://github.com/webpack/webpack/discussions',
        description: 'Webpack GitHub Discussions',
        logoUrl: 'https://github.com/webpack.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-webpack',
      },
      {
        name: 'SolidJS',
        url: 'https://github.com/solidjs/solid/discussions',
        description: 'SolidJS GitHub Discussions',
        logoUrl: 'https://github.com/solidjs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-solid',
      },
      {
        name: 'SolidStart',
        url: 'https://github.com/solidjs/solid-start/discussions',
        description: 'SolidStart GitHub Discussions',
        logoUrl: 'https://github.com/solidjs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-solid-start',
      },
      {
        name: 'Storybook',
        url: 'https://github.com/storybookjs/storybook/discussions',
        description: 'Storybook GitHub Discussions',
        logoUrl: 'https://github.com/storybookjs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-storybook',
      },
      {
        name: 'Rspack',
        url: 'https://github.com/web-infra-dev/rspack/discussions',
        description: 'Rspack GitHub Discussions',
        logoUrl: 'https://github.com/web-infra-dev.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-rspack',
      },
      {
        name: 'Rolldown',
        url: 'https://github.com/rolldown/rolldown/discussions',
        description: 'Rolldown GitHub Discussions',
        logoUrl: 'https://github.com/rolldown.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-rolldown',
      },
      {
        name: 'React Native Community Discussions & Proposals',
        url: 'https://github.com/react-native-community/discussions-and-proposals/discussions',
        description: 'React Native Community Discussions & Proposals GitHub Discussions',
        logoUrl: 'https://github.com/react-native-community.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-discussions-and-proposals',
      },
      {
        name: 'React Compiler Working Group',
        url: 'https://github.com/reactwg/react-compiler/discussions',
        description: 'React Compiler Working Group GitHub Discussions',
        logoUrl: 'https://github.com/reactwg.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-react-compiler',
      },
      {
        name: 'Symfony',
        url: 'https://github.com/symfony/symfony/discussions',
        description: 'Symfony GitHub Discussions',
        logoUrl: 'https://github.com/symfony.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-symfony',
      },
      {
        name: 'Laravel Framework',
        url: 'https://github.com/laravel/framework/discussions',
        description: 'Laravel Framework GitHub Discussions',
        logoUrl: 'https://github.com/laravel.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-framework',
      },
      {
        name: 'WordPress Gutenberg',
        url: 'https://github.com/WordPress/gutenberg/discussions',
        description: 'WordPress Gutenberg GitHub Discussions',
        logoUrl: 'https://github.com/WordPress.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-gutenberg',
      },
      {
        name: 'FastAPI',
        url: 'https://github.com/fastapi/fastapi/discussions',
        description: 'FastAPI GitHub Discussions',
        logoUrl: 'https://github.com/fastapi.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-fastapi',
      },
      {
        name: 'SQLModel',
        url: 'https://github.com/fastapi/sqlmodel/discussions',
        description: 'SQLModel GitHub Discussions',
        logoUrl: 'https://github.com/fastapi.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-sqlmodel',
      },
      {
        name: 'Apache DataFusion',
        url: 'https://github.com/apache/datafusion/discussions',
        description: 'Apache DataFusion GitHub Discussions',
        logoUrl: 'https://github.com/apache.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-datafusion',
      },
      {
        name: 'Typer',
        url: 'https://github.com/tiangolo/typer/discussions',
        description: 'Typer GitHub Discussions',
        logoUrl: 'https://github.com/tiangolo.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-typer',
      },
      {
        name: 'Full Stack FastAPI Template',
        url: 'https://github.com/tiangolo/full-stack-fastapi-template/discussions',
        description: 'Full Stack FastAPI Template GitHub Discussions',
        logoUrl: 'https://github.com/tiangolo.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-full-stack-fastapi-template',
      },
      {
        name: 'Prisma',
        url: 'https://github.com/prisma/prisma/discussions',
        description: 'Prisma GitHub Discussions',
        logoUrl: 'https://github.com/prisma.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-prisma',
      },
      {
        name: 'dotnet/roslyn',
        url: 'https://github.com/dotnet/roslyn/discussions',
        description: 'dotnet/roslyn GitHub Discussions',
        logoUrl: 'https://github.com/dotnet.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-roslyn',
      },
      {
        name: 'LLVM Discussion',
        url: 'https://discourse.llvm.org/',
        description: 'LLVM Discussion community forum',
        logoUrl: 'https://discourse.llvm.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Posit Community (RStudio/tidyverse)',
        url: 'https://forum.posit.co/',
        description: 'Posit Community (RStudio/tidyverse) community forum',
        logoUrl: 'https://forum.posit.co/favicon.ico',
        tier: 2,
      },
      {
        name: 'three.js',
        url: 'https://discourse.threejs.org/',
        description: 'three.js community forum',
        logoUrl: 'https://discourse.threejs.org/favicon.ico',
        tier: 2,
      },
      {
        name: 'Rust Users',
        url: 'https://users.rust-lang.org/',
        description: 'Rust community forum for users',
        logoUrl: 'https://www.rust-lang.org/logos/rust-logo-512x512.png',
        tier: 1,
      },
      {
        name: 'Rust Internals',
        url: 'https://internals.rust-lang.org/',
        description: 'Rust development and governance',
        logoUrl: 'https://www.rust-lang.org/logos/rust-logo-512x512.png',
        tier: 1,
      },
      {
        name: 'Swift Forums',
        url: 'https://forums.swift.org/',
        description: 'Apple Swift language governance',
        logoUrl: 'https://developer.apple.com/swift/images/swift-og.png',
        tier: 1,
      },
      {
        name: 'Julia',
        url: 'https://discourse.julialang.org/',
        description: 'Julia language community and governance',
        logoUrl: 'https://julialang.org/assets/infra/logo.svg',
        tier: 1,
      },
      {
        name: 'Elixir Forum',
        url: 'https://elixirforum.com/',
        description: 'Elixir language community',
        logoUrl: 'https://elixir-lang.org/images/logo/logo.png',
        tier: 2,
      },
      {
        name: 'Haskell Discourse',
        url: 'https://discourse.haskell.org/',
        description: 'Haskell community and Haskell Foundation',
        logoUrl: 'https://www.haskell.org/img/haskell-logo.svg',
        tier: 2,
      },
      {
        name: 'OCaml Discuss',
        url: 'https://discuss.ocaml.org/',
        description: 'OCaml community discussions',
        logoUrl: 'https://ocaml.org/img/colour-logo.svg',
        tier: 2,
      },
      {
        name: 'Clojure Forum',
        url: 'https://clojureverse.org/',
        description: 'Clojure community discussions',
        logoUrl: 'https://clojure.org/images/clojure-logo-120b.png',
        tier: 2,
      },
    
      {
        name: 'Django Forum',
        url: 'https://forum.djangoproject.com/',
        description: 'Django web framework and DSF governance',
        logoUrl: 'https://static.djangoproject.com/img/logos/django-logo-positive.png',
        tier: 1,
      },
      {
        name: 'Ember.js',
        url: 'https://discuss.emberjs.com/',
        description: 'Ember.js framework governance',
        logoUrl: 'https://emberjs.com/images/brand/ember-tomster-lockup-4c.svg',
        tier: 2,
      },
      {
        name: 'Godot Forum',
        url: 'https://forum.godotengine.org/',
        description: 'Godot game engine governance and funding',
        logoUrl: 'https://godotengine.org/assets/press/logo_large_color_dark.png',
        tier: 1,
      },
      {
        name: 'Blender DevTalk',
        url: 'https://devtalk.blender.org/',
        description: 'Blender development and funding',
        logoUrl: 'https://download.blender.org/branding/community/blender_community_badge_white.png',
        tier: 1,
      },
      {
        name: 'Obsidian Forum',
        url: 'https://forum.obsidian.md/',
        description: 'Obsidian knowledge base app community',
        logoUrl: 'https://obsidian.md/images/obsidian-logo-gradient.svg',
        tier: 2,
      },
      {
        name: 'Home Assistant',
        url: 'https://community.home-assistant.io/',
        description: 'Home automation platform',
        logoUrl: 'https://www.home-assistant.io/images/home-assistant-logo.svg',
        tier: 1,
      },
      {
        name: 'Discourse Meta',
        url: 'https://meta.discourse.org/',
        description: 'Discourse platform itself; governance and development',
        logoUrl: 'https://d11a6trkgmumsb.cloudfront.net/original/3X/c/b/cb4bec8501c1027e386940c479d91593aeb61b4d.svg',
        tier: 2,
      },
    
      {
        name: 'NixOS Discourse',
        url: 'https://discourse.nixos.org/',
        description: 'Nix/NixOS governance and funding',
        logoUrl: 'https://nixos.org/logo/nixos-logo-only-hires.png',
        tier: 1,
      },
      {
        name: 'Fedora Discussion',
        url: 'https://discussion.fedoraproject.org/',
        description: 'Fedora governance and development',
        logoUrl: 'https://fedoraproject.org/w/uploads/2/2d/Logo_fedoralogo.png',
        tier: 1,
      },
      {
        name: 'Ubuntu Discourse',
        url: 'https://discourse.ubuntu.com/',
        description: 'Ubuntu community governance',
        logoUrl: 'https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png',
        tier: 1,
      },
      {
        name: 'GNOME Discourse',
        url: 'https://discourse.gnome.org/',
        description: 'GNOME governance and GNOME Foundation',
        logoUrl: 'https://www.gnome.org/wp-content/uploads/2020/08/cropped-gnome-logo.png',
        tier: 1,
      },
      {
        name: 'KDE Discuss',
        url: 'https://discuss.kde.org/',
        description: 'KDE governance',
        logoUrl: 'https://kde.org/stuff/clipart/logo/kde-logo-white-blue-rounded-source.svg',
        tier: 1,
      },
      {
        name: 'Mozilla Discourse',
        url: 'https://discourse.mozilla.org/',
        description: 'Mozilla community and grants',
        logoUrl: 'https://www.mozilla.org/media/img/mozorg/moz-logo-bw-rgb.svg',
        tier: 1,
      },
      {
        name: 'Lets Encrypt Community',
        url: 'https://community.letsencrypt.org/',
        description: 'ISRG/Lets Encrypt discussions',
        logoUrl: 'https://letsencrypt.org/images/le-logo-twitter-noalpha.png',
        tier: 2,
      },
      {
        name: 'OpenStreetMap',
        url: 'https://community.openstreetmap.org/',
        description: 'OSM governance and OSMF',
        logoUrl: 'https://wiki.openstreetmap.org/w/images/7/79/Public-images-osm_logo.svg',
        tier: 2,
      },
      {
        name: 'Kubernetes',
        url: 'https://discuss.kubernetes.io/',
        description: 'Container orchestration community and governance',
        tier: 1,
      },
      {
        name: 'Jupyter',
        url: 'https://discourse.jupyter.org/',
        description: 'Jupyter notebooks and scientific computing',
        tier: 1,
      },
      {
        name: 'HashiCorp',
        url: 'https://discuss.hashicorp.com/',
        description: 'Terraform, Vault, Consul infrastructure tools',
        tier: 1,
      },
      {
        name: 'Elastic',
        url: 'https://discuss.elastic.co/',
        description: 'Elasticsearch, Kibana, and observability stack',
        tier: 1,
      },
      {
        name: 'Kotlin',
        url: 'https://discuss.kotlinlang.org/',
        description: 'Kotlin language development and community',
        tier: 2,
      },
      {
        name: 'Ruby on Rails',
        url: 'https://discuss.rubyonrails.org/',
        description: 'Rails framework development and governance',
        tier: 2,
      },
      {
        name: 'Ansible',
        url: 'https://forum.ansible.com/',
        description: 'Ansible automation platform community',
        tier: 2,
      },
      // GitHub Discussions — Open Source
      {
        name: 'Next.js',
        url: 'https://github.com/vercel/next.js/discussions',
        description: 'Next.js framework discussions',
        logoUrl: 'https://github.com/vercel.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-nextjs',
      },
      {
        name: 'Deno',
        url: 'https://github.com/denoland/deno/discussions',
        description: 'Deno runtime discussions and proposals',
        logoUrl: 'https://github.com/denoland.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-deno',
      },
      {
        name: 'Bun',
        url: 'https://github.com/oven-sh/bun/discussions',
        description: 'Bun JavaScript runtime discussions',
        logoUrl: 'https://github.com/oven-sh.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-bun',
      },
      {
        name: 'Vue.js',
        url: 'https://github.com/vuejs/core/discussions',
        description: 'Vue.js framework discussions and RFCs',
        logoUrl: 'https://github.com/vuejs.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-vue',
      },
      {
        name: 'Svelte',
        url: 'https://github.com/sveltejs/svelte/discussions',
        description: 'Svelte framework discussions',
        logoUrl: 'https://github.com/sveltejs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-svelte',
      },
      {
        name: 'Angular',
        url: 'https://github.com/angular/angular/discussions',
        description: 'Angular framework discussions',
        logoUrl: 'https://github.com/angular.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-angular',
      },
      {
        name: 'Nuxt',
        url: 'https://github.com/nuxt/nuxt/discussions',
        description: 'Nuxt Vue framework discussions',
        logoUrl: 'https://github.com/nuxt.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-nuxt',
      },
      {
        name: 'Tailwind CSS',
        url: 'https://github.com/tailwindlabs/tailwindcss/discussions',
        description: 'Tailwind CSS utility framework discussions',
        logoUrl: 'https://github.com/tailwindlabs.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-tailwindcss',
      },
      {
        name: 'Remix',
        url: 'https://github.com/remix-run/remix/discussions',
        description: 'Remix full-stack web framework discussions',
        logoUrl: 'https://github.com/remix-run.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-remix',
      },
      {
        name: 'Turborepo',
        url: 'https://github.com/vercel/turbo/discussions',
        description: 'Turborepo monorepo build system discussions',
        logoUrl: 'https://github.com/vercel.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-turbo',
      },
      {
        name: 'pnpm',
        url: 'https://github.com/pnpm/pnpm/discussions',
        description: 'pnpm package manager discussions',
        logoUrl: 'https://github.com/pnpm.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-pnpm',
      },
      {
        name: 'shadcn/ui',
        url: 'https://github.com/shadcn-ui/ui/discussions',
        description: 'shadcn/ui component library discussions',
        logoUrl: 'https://github.com/shadcn-ui.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-shadcn-ui',
      },
      {
        name: 'Biome',
        url: 'https://github.com/biomejs/biome/discussions',
        description: 'Biome JS/TS toolchain discussions',
        logoUrl: 'https://github.com/biomejs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-biome',
      },
      {
        name: 'OpenTofu',
        url: 'https://github.com/opentofu/opentofu/discussions',
        description: 'OpenTofu infrastructure-as-code discussions',
        logoUrl: 'https://github.com/opentofu.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-opentofu',
      },
      {
        name: 'Grafana',
        url: 'https://github.com/grafana/grafana/discussions',
        description: 'Grafana observability platform discussions',
        logoUrl: 'https://github.com/grafana.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-grafana',
      },
      {
        name: 'Prometheus',
        url: 'https://github.com/prometheus/prometheus/discussions',
        description: 'Prometheus monitoring system discussions',
        logoUrl: 'https://github.com/prometheus.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-prometheus',
      },
      {
        name: 'Tokio',
        url: 'https://github.com/tokio-rs/tokio/discussions',
        description: 'Tokio Rust async runtime discussions',
        logoUrl: 'https://github.com/tokio-rs.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-tokio',
      },
      {
        name: 'Typst',
        url: 'https://github.com/typst/typst/discussions',
        description: 'Typst typesetting system discussions',
        logoUrl: 'https://github.com/typst.png',
        tier: 3,
        sourceType: 'github',
        sourceId: 'github-typst',
      },
      {
        name: 'Fresh',
        url: 'https://github.com/denoland/fresh/discussions',
        description: 'Fresh web framework for Deno discussions',
        logoUrl: 'https://github.com/denoland.png',
        tier: 3,
        sourceType: 'github',
        sourceId: 'github-deno-fresh',
      },
      {
        name: 'Go',
        url: 'https://github.com/golang/go/discussions',
        description: 'Go programming language discussions',
        logoUrl: 'https://github.com/golang.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-golang',
      },
      {
        name: 'VS Code',
        url: 'https://github.com/microsoft/vscode-discussions/discussions',
        description: 'Visual Studio Code discussions',
        logoUrl: 'https://github.com/microsoft.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-vscode',
      },
      {
        name: 'OXC',
        url: 'https://github.com/oxc-project/oxc/discussions',
        description: 'OXC JavaScript toolchain discussions',
        logoUrl: 'https://github.com/oxc-project.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-oxc',
      },
      {
        name: 'Gleam',
        url: 'https://github.com/gleam-lang/gleam/discussions',
        description: 'Gleam programming language discussions',
        logoUrl: 'https://github.com/gleam-lang.png',
        tier: 3,
        sourceType: 'github',
        sourceId: 'github-gleam',
      },
      {
        name: 'Ruff',
        url: 'https://github.com/astral-sh/ruff/discussions',
        description: 'Ruff Python linter and formatter discussions',
        logoUrl: 'https://github.com/astral-sh.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-ruff',
      },
      {
        name: 'TypeScript Native',
        url: 'https://github.com/microsoft/typescript-go/discussions',
        description: 'TypeScript native port (Go) discussions',
        logoUrl: 'https://github.com/microsoft.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-typescript-go',
      },
      {
        name: 'Astro',
        url: 'https://github.com/withastro/roadmap/discussions',
        description: 'Astro web framework roadmap and feature discussions',
        logoUrl: 'https://github.com/withastro.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-astro-roadmap',
      },
      {
        name: 'Homebrew',
        url: 'https://github.com/Homebrew/discussions/discussions',
        description: 'Homebrew package manager discussions',
        logoUrl: 'https://github.com/Homebrew.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-homebrew',
      },
      {
        name: 'Godot Proposals',
        url: 'https://github.com/godotengine/godot-proposals/discussions',
        description: 'Godot engine feature proposals and discussions',
        logoUrl: 'https://github.com/godotengine.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-godot-proposals',
      },
      {
        name: 'Tauri',
        url: 'https://github.com/tauri-apps/tauri/discussions',
        description: 'Tauri desktop app framework discussions',
        logoUrl: 'https://github.com/tauri-apps.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-tauri',
      },
      {
        name: 'Leptos',
        url: 'https://github.com/leptos-rs/leptos/discussions',
        description: 'Leptos Rust web framework discussions',
        logoUrl: 'https://github.com/leptos-rs.png',
        tier: 3,
        sourceType: 'github',
        sourceId: 'github-leptos',
      },
      {
        name: 'Zed Editor',
        url: 'https://github.com/zed-industries/zed/discussions',
        description: 'Zed code editor discussions',
        logoUrl: 'https://github.com/zed-industries.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-zed',
      },
      {
        name: 'Ziggit (Zig)',
        url: 'https://ziggit.dev/',
        description: 'De-facto Zig language community forum',
        logoUrl: 'https://avatars.githubusercontent.com/u/27973237',
        tier: 1,
      },
      {
        name: 'Fly.io Community',
        url: 'https://community.fly.io/',
        description: 'Fly.io app platform and edge infrastructure community',
        logoUrl: 'https://avatars.githubusercontent.com/u/22525303',
        tier: 1,
      },
      {
        name: 'Snapcraft',
        url: 'https://forum.snapcraft.io/',
        description: 'Canonical snap packaging and Snap Store community',
        logoUrl: 'https://avatars.githubusercontent.com/u/4218408',
        tier: 2,
      },
      {
        name: 'Crystal Language',
        url: 'https://forum.crystal-lang.org/',
        description: 'Crystal programming language community',
        logoUrl: 'https://avatars.githubusercontent.com/u/6539796',
        tier: 2,
      },
      {
        name: 'Caddy',
        url: 'https://caddy.community/',
        description: 'Caddy web server / reverse proxy community',
        logoUrl: 'https://avatars.githubusercontent.com/u/12953524',
        tier: 1,
      },
      {
        name: 'Traefik',
        url: 'https://community.traefik.io/',
        description: 'Traefik proxy and Traefik Hub community',
        logoUrl: 'https://avatars.githubusercontent.com/u/19199651',
        tier: 1,
      },
      {
        name: 'OpenSearch',
        url: 'https://forum.opensearch.org/',
        description: 'OpenSearch (search + analytics fork of Elasticsearch) community',
        logoUrl: 'https://avatars.githubusercontent.com/u/80134844',
        tier: 1,
      },
      {
        name: 'Vercel Community',
        url: 'https://community.vercel.com/',
        description: 'Vercel deployment platform and Next.js operational community',
        logoUrl: 'https://avatars.githubusercontent.com/u/14985020',
        tier: 1,
      },
      {
        name: 'GitLab Community',
        url: 'https://forum.gitlab.com/',
        description: 'GitLab CI/CD, source control, and DevOps community',
        logoUrl: 'https://avatars.githubusercontent.com/u/1086321',
        tier: 1,
      },
      {
        name: 'Gradle',
        url: 'https://discuss.gradle.org/',
        description: 'Gradle JVM build tool community',
        logoUrl: 'https://avatars.githubusercontent.com/u/124156',
        tier: 1,
      },
      {
        name: 'Racket',
        url: 'https://racket.discourse.group/',
        description: 'Racket programming language community',
        logoUrl: 'https://avatars.githubusercontent.com/u/9978613',
        tier: 2,
      },
      {
        name: 'Phaser',
        url: 'https://phaser.discourse.group/',
        description: 'Phaser HTML5 game framework community',
        logoUrl: 'https://avatars.githubusercontent.com/u/2068011',
        tier: 2,
      },
      {
        name: 'Linux Containers (Incus)',
        url: 'https://discuss.linuxcontainers.org/',
        description: 'Incus / LXC / LXD system container community',
        logoUrl: 'https://avatars.githubusercontent.com/u/11951777',
        tier: 2,
      },
      {
        name: 'InfluxData',
        url: 'https://community.influxdata.com/',
        description: 'InfluxDB time-series database community',
        logoUrl: 'https://avatars.githubusercontent.com/u/5713248',
        tier: 2,
      },
      {
        name: 'openHAB',
        url: 'https://community.openhab.org/',
        description: 'openHAB open-source home automation community',
        logoUrl: 'https://avatars.githubusercontent.com/u/4393662',
        tier: 2,
      },
      {
        name: 'Metabase',
        url: 'https://discourse.metabase.com/',
        description: 'Metabase open-source BI and analytics community',
        logoUrl: 'https://avatars.githubusercontent.com/u/12463434',
        tier: 2,
      },
      {
        name: 'Restic',
        url: 'https://forum.restic.net/',
        description: 'Restic encrypted backup tool community',
        logoUrl: 'https://avatars.githubusercontent.com/u/12116167',
        tier: 2,
      },
      {
        name: 'OctoPrint',
        url: 'https://community.octoprint.org/',
        description: '3D-printing OctoPrint host software community',
        logoUrl: 'https://avatars.githubusercontent.com/u/12612917',
        tier: 2,
      },
      {
        name: 'Shopify Developer',
        url: 'https://community.shopify.dev/',
        description: 'Shopify developer platform (APIs, apps, Hydrogen) community',
        logoUrl: 'https://avatars.githubusercontent.com/u/8085',
        tier: 2,
      },
      {
        name: 'Argo CD',
        url: 'https://github.com/argoproj/argo-cd/discussions',
        description: 'Argo CD Kubernetes GitOps discussions',
        logoUrl: 'https://github.com/argoproj.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-argo-cd',
      },
      {
        name: 'Cilium',
        url: 'https://github.com/cilium/cilium/discussions',
        description: 'Cilium eBPF-based networking and security discussions',
        logoUrl: 'https://github.com/cilium.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-cilium',
      },
      {
        name: 'OpenTelemetry Collector',
        url: 'https://github.com/open-telemetry/opentelemetry-collector/discussions',
        description: 'OpenTelemetry Collector discussions (telemetry pipelines)',
        logoUrl: 'https://github.com/open-telemetry.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-otel-collector',
      },
      {
        name: 'Vite',
        url: 'https://github.com/vitejs/vite/discussions',
        description: 'Vite frontend build tool discussions',
        logoUrl: 'https://github.com/vitejs.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-vite',
      },
      {
        name: 'TanStack Query',
        url: 'https://github.com/TanStack/query/discussions',
        description: 'TanStack Query (React Query / Vue Query / etc.) discussions',
        logoUrl: 'https://github.com/TanStack.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-tanstack-query',
      },
      {
        name: 'Neovim',
        url: 'https://github.com/neovim/neovim/discussions',
        description: 'Neovim editor discussions',
        logoUrl: 'https://github.com/neovim.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-neovim',
      },
      {
        name: 'DuckDB',
        url: 'https://github.com/duckdb/duckdb/discussions',
        description: 'DuckDB embedded analytical database discussions',
        logoUrl: 'https://github.com/duckdb.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-duckdb',
      },
      {
        name: 'ClickHouse',
        url: 'https://github.com/ClickHouse/ClickHouse/discussions',
        description: 'ClickHouse columnar database discussions',
        logoUrl: 'https://github.com/ClickHouse.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-clickhouse',
      },
      {
        name: 'Supabase',
        url: 'https://github.com/supabase/supabase/discussions',
        description: 'Supabase open-source Firebase alternative discussions',
        logoUrl: 'https://github.com/supabase.png',
        tier: 1,
        sourceType: 'github',
        sourceId: 'github-supabase',
      },
      {
        name: 'Flux CD',
        url: 'https://github.com/fluxcd/flux2/discussions',
        description: 'Flux GitOps for Kubernetes discussions',
        logoUrl: 'https://github.com/fluxcd.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-flux2',
      },
      {
        name: 'KEDA',
        url: 'https://github.com/kedacore/keda/discussions',
        description: 'KEDA event-driven Kubernetes autoscaling discussions',
        logoUrl: 'https://github.com/kedacore.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-keda',
      },
      {
        name: 'k3s',
        url: 'https://github.com/k3s-io/k3s/discussions',
        description: 'k3s lightweight Kubernetes discussions',
        logoUrl: 'https://github.com/k3s-io.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-k3s',
      },
      {
        name: 'Longhorn',
        url: 'https://github.com/longhorn/longhorn/discussions',
        description: 'Longhorn distributed block storage for Kubernetes',
        logoUrl: 'https://github.com/longhorn.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-longhorn',
      },
      {
        name: 'Pulumi',
        url: 'https://github.com/pulumi/pulumi/discussions',
        description: 'Pulumi infrastructure-as-code discussions',
        logoUrl: 'https://github.com/pulumi.png',
        tier: 2,
        sourceType: 'github',
        sourceId: 'github-pulumi',
      },
      {
        name: 'Hacker News · Open Source',
        url: 'https://news.ycombinator.com/#oss',
        description: 'Top HN stories on open-source projects, maintainers, and licensing',
        logoUrl: 'https://news.ycombinator.com/favicon.ico',
        tier: 1,
        sourceType: 'hackernews',
        sourceId: 'hn-oss',
      },
      {
        name: 'Lobsters · Open Source',
        url: 'https://lobste.rs/t/programming,rust,go,python,javascript,web,devops,compsci',
        description: 'Recent Lobsters discussions on programming and open source',
        logoUrl: 'https://lobste.rs/favicon.ico',
        tier: 2,
        sourceType: 'lobsters',
        sourceId: 'lobsters-oss',
      },

    ],
  },
];

/**
 * Flat list of all forum presets
 */
export const ALL_FORUM_PRESETS: ForumPreset[] = FORUM_CATEGORIES.flatMap(
  (category) => category.forums
);

/**
 * Get forums by tier
 */
export function getForumsByTier(tier: 1 | 2 | 3): ForumPreset[] {
  return ALL_FORUM_PRESETS.filter((forum) => forum.tier === tier);
}

/**
 * Get forums by category ID
 */
export function getForumsByCategory(categoryId: string): ForumPreset[] {
  const category = FORUM_CATEGORIES.find((c) => c.id === categoryId);
  return category?.forums ?? [];
}

/**
 * Get total forum count
 */
export function getTotalForumCount(): number {
  return ALL_FORUM_PRESETS.length;
}

/**
 * Search forums by name, description, or token
 */
/**
 * Build lookup: normalized URL → category id (crypto, ai, oss)
 * Includes external sources keyed as `external:{sourceId}`
 */
export function buildUrlCategoryMap(externalSources: Array<{ id: string; category: string; enabled: boolean }>): Map<string, string> {
  const map = new Map<string, string>();
  for (const cat of FORUM_CATEGORIES) {
    for (const forum of cat.forums) {
      map.set(forum.url.replace(/\/$/, '').toLowerCase(), cat.id);
    }
  }
  for (const src of externalSources) {
    if (src.enabled) {
      map.set(`external:${src.id}`, src.category);
    }
  }
  return map;
}

/**
 * Build lookup: normalized URL → forum display name
 */
export function buildUrlForumNameMap(): Map<string, string> {
  const map = new Map<string, string>();
  for (const cat of FORUM_CATEGORIES) {
    for (const forum of cat.forums) {
      map.set(forum.url.replace(/\/$/, '').toLowerCase(), forum.name);
    }
  }
  return map;
}

export function searchForums(query: string): ForumPreset[] {
  const lowerQuery = query.toLowerCase().replace(/^\$/, '');
  return ALL_FORUM_PRESETS.filter(
    (forum) =>
      forum.name.toLowerCase().includes(lowerQuery) ||
      forum.description?.toLowerCase().includes(lowerQuery) ||
      forum.token?.toLowerCase().includes(lowerQuery)
  );
}
