import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {getDb,initializeSchema} from '../src/lib/db';
import {ingestDocuments,searchIntelligence,classifyIntelligenceDocument,listIntelligence,reviewIntelligence,migrateLegacyIntelligence,publishFreshIntelligence,recordOutboundLinks} from '../src/lib/intelligenceStore';
import {validateCorpusExtraction,type CorpusClassify} from '../src/lib/corpusClassifier';
import {ensureWatches,saveWatch,runWatch,getWatchMatches,type WatchEvaluator} from '../src/lib/semanticWatches';
import {acquireSurfaceGroup} from '../src/lib/surfaceAcquisition';
import {fetchStrictFeed} from '../src/lib/strictFeed';
import {recordSurfaceAttempt,recordTopicSurfaceMatches,getTopicSurfaceProvenance,dueSurfaceGroups,getSourceHealth,getSurfaceHealth} from '../src/lib/surfaceObservability';
import type {SurfaceDefinition} from '../src/lib/sourceRegistry';
import {setSourcePaused,intelligenceTrace} from '../src/lib/operatorIntelligence';
import {registerSource,ingestRegisteredSource} from '../src/lib/sourceAdapters';
import {runNativeCandidateScan} from '../src/lib/nativeLaneScan';
import {markItemsNotified} from '../src/lib/grantsStore';
import {initializeCorpusSchema,startCorpusJob,extendCorpusJob,corpusStatus} from '../src/lib/corpusStore';
import {runCorpusTick,type CorpusFetch} from '../src/lib/corpusWorker';
const testUrl=process.env.CORPUS_TEST_DATABASE_URL;
if(testUrl)process.env.DATABASE_URL=testUrl;
after(async()=>{if(testUrl)await getDb().end({timeout:5});});
const source='https://forum.example.org';
const fundingQuote='Applications are open for project grants of $100,000.';
const paidQuote='We are hiring an operations consultant for a paid six-week contract.';
const body=fundingQuote+' '+paidQuote+' Heliotrope automation is the project scope. Apply at https://example.org/apply.';
let modelCalls=0;
const classifier:CorpusClassify=async input=>{modelCalls++;await new Promise(r=>setTimeout(r,15));return {model:'fixture-grounded',extraction:validateCorpusExtraction({relevant:true,kind:input.lane==='funding'?'open_call':'paid_work',availability:'open',engagement:input.lane==='funding'?null:'contract',paidEvidence:input.lane==='opportunities',confidence:95,evidence:input.lane==='funding'?fundingQuote:paidQuote,deadline:null,applicationUrl:'https://example.org/apply'},input)};};
const evaluator:WatchEvaluator=async()=>({model:'fixture-watch',output:{matches:true,confidence:90,evidence:fundingQuote,explanation:'The source explicitly offers the threshold amount.',kind:'funding',availability:'open'}});

test('common corpus, durable multi-surface provenance, independent records, semantic watch and reviewed APIs',{skip:!testUrl},async()=>{
  await initializeSchema();await ensureWatches();const db=getDb();
  await db`INSERT INTO ingestion_sources(source_key,name,url,adapter,vertical,managed_by) VALUES(${source},'Fixture source',${source},'discourse','oss','operator') ON CONFLICT DO NOTHING`;
  const groups:SurfaceDefinition[]=['funding','opportunities'].map(l=>({key:source+'|'+l,sourceKey:source,forumUrl:source,protocol:'Fixture source',lane:l as 'funding'|'opportunities',type:'tag',slug:'rfp',feedUrl:source+'/tag/rfp.rss',priority:1,intervalSeconds:3600,enabled:true}));
  for(const g of groups)await db`INSERT INTO source_surface_registry(surface_key,source_key,forum_url,protocol,lane,surface_type,surface_slug,feed_url) VALUES(${g.key},${source},${source},${g.protocol},${g.lane},'tag','rfp',${g.feedUrl}) ON CONFLICT DO NOTHING`;
  let downloads=0;
  const items=await acquireSurfaceGroup(groups,{fetch:async url=>{downloads++;return fetchStrictFeed(url,async()=>new Response(`<rss><channel><item><title>Community bulletin</title><link>${source}/t/community-bulletin/42</link><description><![CDATA[<p>${body}</p>]]></description><pubDate>${new Date(Date.now()-86400000).toUTCString()}</pubDate></item></channel></rss>`));},attempt:recordSurfaceAttempt,matches:recordTopicSurfaceMatches});
  assert.equal(downloads,1);assert.equal(items.length,1);assert.equal(items[0].provenance.length,2);
  const inputs=items.map(i=>({refId:i.refId,sourceKey:source,title:i.title,url:i.url,body:i.body,createdAt:i.publishedAt,historical:true}));
  const docs=await ingestDocuments(inputs),d=docs[0];assert.equal(typeof d.id,'number');
  await ingestDocuments(inputs);assert.equal((await db`SELECT count(*)::int n FROM intelligence_documents WHERE ref_id=${d.ref_id}`)[0].n,1);
  assert.equal((await getTopicSurfaceProvenance(d.ref_id)).length,2);
  const search=await searchIntelligence('heliotrope',source);assert.equal(search.items.length,1);assert.equal(search.items[0].title.includes('Heliotrope'),false);
  const parallel=await Promise.all([classifyIntelligenceDocument(d.id,'opportunities',classifier),classifyIntelligenceDocument(d.id,'opportunities',classifier)]);
  assert.equal(parallel.filter(r=>r.worked).length,1);
  await classifyIntelligenceDocument(d.id,'funding',classifier);assert.equal(modelCalls,2);
  assert.equal((await db`SELECT count(*)::int n FROM intelligence_evaluations WHERE document_id=${d.id}`)[0].n,2);
  assert.equal((await listIntelligence('funding',{limit:100,source,publicOnly:true})).items.length,0);
  const watch=await saveWatch({name:'Large infrastructure funding',instructions:'Find open infrastructure project funding of at least $100,000.',sourceKeys:[source],exclusions:[],enabled:true});
  const first=await runWatch(watch.id,5,evaluator);assert.equal('matched' in first?first.matched:0,1);
  assert.equal((await getWatchMatches(watch.id)).length,1);
  assert.equal('processed' in (await runWatch(watch.id,5,evaluator)),true);
  const repeated=await runWatch(watch.id,5,evaluator);assert.equal('processed' in repeated?repeated.processed:1,0);
  const funding=await reviewIntelligence(d.id,'funding','approve','test-operator','Reviewed both source evidence and opportunity details.');
  const work=await reviewIntelligence(d.id,'opportunities','approve','test-operator','Reviewed actual paid-work wording.');
  assert.notEqual(funding.compatibilityRef,work.compatibilityRef);
  assert.equal((await listIntelligence('funding',{limit:100,source,publicOnly:true})).items.length,1);
  assert.equal((await listIntelligence('opportunities',{limit:100,source,publicOnly:true})).items.length,1);
  const projected=await db`SELECT classification,notified_at FROM grants_items WHERE topic_ref_id=ANY(${[funding.compatibilityRef!,work.compatibilityRef!]})`;
  assert.equal(projected.length,2);assert.ok(projected.every(r=>r.notified_at));
  await reviewIntelligence(d.id,'funding','approve','test-operator','Replay should not duplicate any record.');
  assert.equal((await db`SELECT count(*)::int n FROM grants_items WHERE topic_ref_id=${funding.compatibilityRef!}`)[0].n,1);
  await reviewIntelligence(d.id,'opportunities','withdraw','test-operator','Withdraw work without removing funding.');
  assert.equal((await listIntelligence('funding',{limit:100,source,publicOnly:true})).items.length,1);
  assert.equal((await listIntelligence('opportunities',{limit:100,source,publicOnly:true})).items.length,0);
  await recordOutboundLinks(d.id,body);assert.equal((await db`SELECT count(*)::int n FROM discovery_references WHERE document_id=${d.id}`)[0].n,1);
  const trace=await intelligenceTrace(d.id);assert.equal(trace.provenance.length,2);assert.equal(trace.evaluations.length,2);assert.ok(trace.reviews.length>=3);
  await ingestDocuments([{refId:d.ref_id,sourceKey:source,title:d.title,url:d.url}]);
  assert.equal((await db`SELECT body FROM intelligence_documents WHERE id=${d.id}`)[0].body,body);
  await ingestDocuments([{refId:d.ref_id,sourceKey:source,title:d.title,url:d.url,body:body+' Updated scope.'}]);
  assert.equal((await getWatchMatches(watch.id)).length,0);assert.equal((await listIntelligence('funding',{limit:100,source,publicOnly:true})).items.length,0);
  assert.equal((await db`SELECT status FROM grants_items WHERE topic_ref_id=${funding.compatibilityRef!}`)[0].status,'closed');
  assert.equal((await db`SELECT count(*)::int n FROM document_revisions WHERE document_id=${d.id}`)[0].n,2);
  await assert.rejects(()=>saveWatch({name:'Invalid source',instructions:'Find relevant things here.',sourceKeys:['missing'],exclusions:[],enabled:true}),/unknown_watch_source/);
  await saveWatch({name:'Large infrastructure funding',instructions:'Find open infrastructure funding.',sourceKeys:[source],exclusions:['Heliotrope'],enabled:true},watch.id);
  const excluded=await runWatch(watch.id,5,evaluator);assert.equal('matched' in excluded?excluded.matched:1,0);
  console.log('INTELLIGENCE_E2E '+JSON.stringify({singlePhysicalDownload:true,bothProvenanceLanes:true,bodySearch:true,twoIndependentRecords:true,semanticGroundedWatch:true,reviewedProjection:true,laneWithdrawal:true,hashVersionInvalidation:true,historicalEmails:0}));
});

test('source retry state is idempotent, ordered, shared by physical endpoint and respects pause',{skip:!testUrl},async()=>{
  const db=getDb(),key=source+'|funding',feed=source+'/tag/rfp.rss';
  const at=new Date(),attemptId=randomUUID();
  const failure={surfaceKey:key,forumUrl:source,protocol:'Fixture source',lane:'funding' as const,surfaceType:'tag',surfaceSlug:'rfp',feedUrl:feed,status:'failed' as const,httpStatus:429,parsedItems:0,retrySeconds:3600,attemptedAt:at,completedAt:at,attemptId,errorCode:'http_429'};
  await recordSurfaceAttempt(failure);await recordSurfaceAttempt(failure);
  let row=(await db`SELECT * FROM source_surfaces WHERE surface_key=${key}`)[0];assert.equal(row.consecutive_failures,1);
  assert.ok(row.next_retry_at.getTime()>=at.getTime()+3600000);
  assert.equal((await dueSurfaceGroups(50)).some(g=>g[0].feedUrl===feed),false);
  await recordSurfaceAttempt({...failure,attemptId:randomUUID(),status:'empty',httpStatus:200,attemptedAt:new Date(at.getTime()-60000),completedAt:new Date(at.getTime()-60000)});
  row=(await db`SELECT * FROM source_surfaces WHERE surface_key=${key}`)[0];assert.equal(row.status,'failed');assert.equal(row.consecutive_failures,1);
  await recordSurfaceAttempt({...failure,attemptId:randomUUID(),status:'ok',httpStatus:200,parsedItems:1,attemptedAt:new Date(at.getTime()+1),completedAt:new Date(at.getTime()+1)});
  row=(await db`SELECT * FROM source_surfaces WHERE surface_key=${key}`)[0];assert.equal(row.status,'ok');assert.equal(row.next_retry_at,null);
  await setSourcePaused(source,true);assert.equal((await getSourceHealth()).find(r=>r.source_key===source)?.health,'disabled');
  assert.equal((await getSurfaceHealth()).find(r=>r.surface_key===key)?.status,'disabled');await setSourcePaused(source,false);
  console.log('SURFACE_RETRY_E2E '+JSON.stringify({outOfOrderPreservesState:true,replayIdempotent:true,physicalAliasRetryRespected:true,pauseRespected:true}));
});

test('native ATS adapter enters shared corpus with original dates and no notification',{skip:!testUrl},async()=>{
  const db=getDb();const registered=await registerSource({name:'Fixture Greenhouse',url:'https://boards-api.greenhouse.io/v1/boards/fixture/jobs',adapter:'greenhouse',vertical:'oss'},'test-operator');
  const result=await ingestRegisteredSource(registered.key,async()=>new Response(JSON.stringify({jobs:[{id:123,title:'Operations manager',absolute_url:'https://example.org/careers/123',content:'<p>We are hiring a paid operations manager.</p>',updated_at:new Date().toISOString()}],meta:{total:1}})));
  assert.equal('stored' in result?result.stored:0,1);
  const d=(await db`SELECT * FROM intelligence_documents WHERE source_key=${registered.key}`)[0];
  assert.equal(d.source_created_at,null);assert.equal(d.historical,true);assert.ok(d.body.includes('paid operations manager'));
  const prior=(await db`SELECT count(*)::int n FROM intelligence_documents WHERE source_key=${registered.key}`)[0].n;
  await ingestRegisteredSource(registered.key,async()=>new Response(JSON.stringify({jobs:[],meta:{total:0}})));
  assert.equal((await db`SELECT count(*)::int n FROM intelligence_documents WHERE source_key=${registered.key}`)[0].n,prior);
  assert.equal((await getSourceHealth()).find(r=>r.source_key===registered.key)?.status,'empty');
});

test('native cutover alone admits new source work; migrations and all operator reviews remain suppressed',{skip:!testUrl},async()=>{
  const db=getDb();await db`UPDATE intelligence_settings SET value=jsonb_build_object('at',now()-interval '10 minutes') WHERE name='native-cutover'`;
  const created=new Date(Date.now()-60000).toISOString();
  const candidate={refId:'fixture-fresh-99',forumUrl:source,protocol:'Fixture source',title:'Project funding and paid work',url:source+'/t/work/99',tags:[],body,createdAt:created,bumpedAt:created,signal:'opportunities tag: rfp'};
  const out=await runNativeCandidateScan([candidate],10,classifier);assert.equal(out.classified,2);
  const native=(await db`SELECT id FROM intelligence_documents WHERE ref_id=${candidate.refId}`)[0];
  const records=await db`SELECT notification_state,compatibility_ref FROM funding_records WHERE document_id=${native.id} UNION ALL SELECT notification_state,compatibility_ref FROM opportunity_records WHERE document_id=${native.id}`;
  assert.equal(records.length,2);assert.ok(records.every(r=>r.notification_state==='pending'));
  const projected=await db`SELECT id,notified_at FROM grants_items WHERE topic_ref_id=ANY(${records.map(r=>r.compatibility_ref)})`;
  assert.ok(projected.every(r=>r.notified_at===null));
  await markItemsNotified(projected.map(r=>r.id));
  assert.equal((await db`SELECT notification_state FROM opportunity_records WHERE document_id=${native.id}`)[0].notification_state,'sent');
  const again=await runNativeCandidateScan([candidate],10,classifier);assert.equal(again.classified,0);
  await publishFreshIntelligence(native.id,'opportunities');assert.equal((await db`SELECT notification_state FROM opportunity_records WHERE document_id=${native.id}`)[0].notification_state,'sent');
  await db`INSERT INTO grants_items(topic_ref_id,protocol,vertical,title,url,classification,confidence,kind,first_post_text,notified_at,topic_created_at) VALUES('migration-fixture','Fixture source','oss','Older funding',${source+'/t/old/21'},'GRANT',90,'program_launch',${body},now(),now()-interval '10 days')`;
  let complete=false;for(let i=0;i<10;i++){const migration=await migrateLegacyIntelligence(200);if(migration.complete){complete=true;break;}}
  assert.ok(complete);await migrateLegacyIntelligence(200);
  const migrated=await db`SELECT r.* FROM funding_records r JOIN intelligence_documents d ON d.id=r.document_id WHERE d.ref_id='migration-fixture'`;
  assert.equal(migrated.length,1);assert.equal(migrated[0].notification_state,'sent');assert.equal(migrated[0].review_state,'legacy');
  console.log('CUTOVER_E2E '+JSON.stringify({newPostCutoverOnly:true,independentWatermarks:true,duplicateFree:true,migrationPreservesMail:true,emailsSent:0}));
});

test('bounded backfill resumes a truncated page without skipping remaining topics',{skip:!testUrl},async()=>{
  await initializeCorpusSchema();const db=getDb();
  await db`INSERT INTO forums(url,name,category,tier) VALUES('https://forum.cow.fi/','CoW Protocol','crypto',1) ON CONFLICT(url) DO NOTHING`;
  const at=new Date().toISOString(),created=new Date(Date.now()-86400000).toISOString();
  const topics=[1,2,3,4,5].map(n=>({id:940000+n,title:'Bounded '+n,slug:'bounded-'+n,tags:[],category_id:1,created_at:created,bumped_at:created,pinned:false}));
  const fetch:CorpusFetch=async url=>{
    if(url.includes('latest.json'))return {topic_list:{topics,more_topics_url:''}};
    const n=Number(url.match(/\/(\d+)\.json/)?.[1]);const t=topics.find(t=>t.id===n)!;
    return {...t,post_stream:{posts:[{id:n+100,post_number:1,cooked:'<p>Complete bounded first post '+n+'</p>',created_at:created}]}};
  };
  const id=await startCorpusJob('https://forum.cow.fi',7,at,{maxTopics:2,maxPages:2});
  for(let n=0;n<4;n++)await runCorpusTick(id,fetch);
  let j=(await corpusStatus()).jobs.find(j=>j.id===id)!;assert.equal(j.status,'partial');assert.equal(j.next_page,0);assert.equal(j.discovered,2);
  await extendCorpusJob(id,10,3);for(let n=0;n<5;n++)await runCorpusTick(id,fetch);
  j=(await corpusStatus()).jobs.find(j=>j.id===id)!;assert.equal(j.status,'complete');assert.equal(j.discovered,5);assert.equal(j.fetched,5);
  assert.equal((await runCorpusTick(id,fetch)).worked,false);
  console.log('BACKFILL_EXTENSION_E2E '+JSON.stringify({boundedPartial:true,resumesSamePage:true,allFiveBodies:true,idempotentReplay:true}));
});
