import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import { getDb, initializeSchema } from '../src/lib/db';
import { initializeSurfaceObservabilitySchema, recordSurfaceAttempt, recordTopicSurfaceMatches, getSurfaceHealth, getTopicSurfaceProvenance, signalSurfaceKey } from '../src/lib/surfaceObservability';
const url=process.env.CORPUS_TEST_DATABASE_URL;
if(url) process.env.DATABASE_URL=url;
after(async()=>{if(url) await getDb().end({timeout:5});});
test('surface health distinguishes empty, failure and recovery and preserves multi-lane provenance',{skip:!url},async()=>{
  await initializeSchema(); await initializeSurfaceObservabilitySchema();
  const forum='https://forum.example.org/';
  const funding=signalSurfaceKey({forumUrl:forum,lane:'funding',type:'category',slug:'grants',id:7});
  const roles=signalSurfaceKey({forumUrl:forum,lane:'opportunities',type:'tag',slug:'rfp'});
  const t0=new Date('2026-10-04T10:00:00Z'), t1=new Date('2026-10-04T11:00:00Z'), t2=new Date('2026-10-04T12:00:00Z');
  await recordSurfaceAttempt({surfaceKey:funding,forumUrl:forum,protocol:'Example',lane:'funding',surfaceType:'category',surfaceSlug:'grants',feedUrl:forum+'c/grants/7.rss',status:'empty',httpStatus:200,parsedItems:0,attemptedAt:t0});
  let row=(await getSurfaceHealth()).find((x:any)=>x.surface_key===funding) as any;
  assert.equal(row.status,'empty'); assert.ok(row.succeeded_at); assert.equal(row.consecutive_failures,0);
  await recordSurfaceAttempt({surfaceKey:funding,forumUrl:forum,protocol:'Example',lane:'funding',surfaceType:'category',surfaceSlug:'grants',feedUrl:forum+'c/grants/7.rss',status:'failed',httpStatus:503,parsedItems:0,errorCode:'http_503',attemptedAt:t1});
  row=(await getSurfaceHealth()).find((x:any)=>x.surface_key===funding) as any;
  assert.equal(row.status,'failed'); assert.equal(row.consecutive_failures,1); assert.equal(new Date(row.succeeded_at).toISOString(),t0.toISOString()); assert.ok(row.next_retry_at);
  await recordSurfaceAttempt({surfaceKey:funding,forumUrl:forum,protocol:'Example',lane:'funding',surfaceType:'category',surfaceSlug:'grants',feedUrl:forum+'c/grants/7.rss',status:'ok',httpStatus:200,parsedItems:3,attemptedAt:t2});
  await recordSurfaceAttempt({surfaceKey:roles,forumUrl:forum,protocol:'Example',lane:'opportunities',surfaceType:'tag',surfaceSlug:'rfp',feedUrl:forum+'tag/rfp.rss',status:'ok',httpStatus:200,parsedItems:1,attemptedAt:t2});
  row=(await getSurfaceHealth()).find((x:any)=>x.surface_key===funding) as any;
  assert.equal(row.status,'ok'); assert.equal(row.parsed_items,3); assert.equal(row.consecutive_failures,0); assert.equal(row.next_retry_at,null);
  await recordTopicSurfaceMatches([{topicRefId:'example-42',surfaceKey:funding,lane:'funding'},{topicRefId:'example-42',surfaceKey:roles,lane:'opportunities'}]);
  await recordTopicSurfaceMatches([{topicRefId:'example-42',surfaceKey:funding,lane:'funding'}]);
  const provenance=await getTopicSurfaceProvenance('example-42') as any[];
  assert.equal(provenance.length,2); assert.deepEqual(new Set(provenance.map(x=>x.lane)),new Set(['funding','opportunities']));
  console.log('SURFACE_OBSERVABILITY_PROOF '+JSON.stringify({emptyVsFailure:true,recovery:true,multiLaneProvenance:true,duplicateDownloadsRequired:false}));
});
