import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import { getDb, initializeSchema } from '../src/lib/db';
import { initializeSurfaceObservabilitySchema, recordSurfaceAttempt, recordTopicSurfaceMatches, getSurfaceHealth, getTopicSurfaceProvenance, signalSurfaceKey } from '../src/lib/surfaceObservability';
const url=process.env.CORPUS_TEST_DATABASE_URL;
if(url) process.env.DATABASE_URL=url;
after(async()=>{if(url) await getDb().end({timeout:5});});
test('surface health distinguishes empty, failure and recovery and preserves multi-lane provenance',{skip:!url},async()=>{
  await initializeSchema(); await initializeSurfaceObservabilitySchema();
  const forum='https://forum.example.org/';
  const funding=signalSurfaceKey({forumUrl:forum,lane:'funding',type:'category',slug:'grants',id:7});
  const roles=signalSurfaceKey({forumUrl:forum,lane:'opportunities',type:'tag',slug:'rfp'});
  const db=getDb();
  for(const [key,lane,type,slug] of [[funding,'funding','category','grants'],[roles,'opportunities','tag','rfp']])
    await db`INSERT INTO source_surface_registry(surface_key,source_key,forum_url,protocol,lane,surface_type,surface_slug,feed_url) VALUES(${key},${forum},${forum},'Example',${lane},${type},${slug},${forum+'test.rss'}) ON CONFLICT DO NOTHING`;
  const t0=new Date(Date.now()-120000),t1=new Date(Date.now()-60000),t2=new Date();
  await recordSurfaceAttempt({surfaceKey:funding,forumUrl:forum,protocol:'Example',lane:'funding',surfaceType:'category',surfaceSlug:'grants',feedUrl:forum+'c/grants/7.rss',status:'empty',httpStatus:200,parsedItems:0,attemptedAt:t0});
  type HealthRow = { surface_key:string; status:string; succeeded_at:Date|null; consecutive_failures:number; next_retry_at:Date|null; parsed_items:number };
  let row=(await getSurfaceHealth() as unknown as HealthRow[]).find(x=>x.surface_key===funding)!;
  assert.equal(row.status,'empty'); assert.ok(row.succeeded_at); assert.equal(row.consecutive_failures,0);
  await recordSurfaceAttempt({surfaceKey:funding,forumUrl:forum,protocol:'Example',lane:'funding',surfaceType:'category',surfaceSlug:'grants',feedUrl:forum+'c/grants/7.rss',status:'failed',httpStatus:503,parsedItems:0,errorCode:'http_503',attemptedAt:t1});
  row=(await getSurfaceHealth() as unknown as HealthRow[]).find(x=>x.surface_key===funding)!;
  assert.equal(row.status,'failed'); assert.equal(row.consecutive_failures,1); assert.ok(row.succeeded_at); assert.equal(row.succeeded_at!.toISOString(),t0.toISOString()); assert.ok(row.next_retry_at);
  await recordSurfaceAttempt({surfaceKey:funding,forumUrl:forum,protocol:'Example',lane:'funding',surfaceType:'category',surfaceSlug:'grants',feedUrl:forum+'c/grants/7.rss',status:'ok',httpStatus:200,parsedItems:3,attemptedAt:t2});
  await recordSurfaceAttempt({surfaceKey:roles,forumUrl:forum,protocol:'Example',lane:'opportunities',surfaceType:'tag',surfaceSlug:'rfp',feedUrl:forum+'tag/rfp.rss',status:'ok',httpStatus:200,parsedItems:1,attemptedAt:t2});
  row=(await getSurfaceHealth() as unknown as HealthRow[]).find(x=>x.surface_key===funding)!;
  assert.equal(row.status,'ok'); assert.equal(row.parsed_items,3); assert.equal(row.consecutive_failures,0); assert.equal(row.next_retry_at,null);
  await recordTopicSurfaceMatches([{topicRefId:'example-42',surfaceKey:funding,lane:'funding'},{topicRefId:'example-42',surfaceKey:roles,lane:'opportunities'}]);
  await recordTopicSurfaceMatches([{topicRefId:'example-42',surfaceKey:funding,lane:'funding'}]);
  const provenance=await getTopicSurfaceProvenance('example-42') as unknown as Array<{lane:string}>;
  assert.equal(provenance.length,2); assert.deepEqual(new Set(provenance.map(x=>x.lane)),new Set(['funding','opportunities']));
  console.log('SURFACE_OBSERVABILITY_PROOF '+JSON.stringify({emptyVsFailure:true,recovery:true,multiLaneProvenance:true,duplicateMatchRows:false}));
});
