'use client';
import {useState} from 'react';
import Link from 'next/link';
type Row=Record<string,unknown>;
type Snapshot={sources:Row[];surfaces:Row[];documents:Row;evaluations:Row[];lanes:Row[];watches:Row[];discoveries:Row[];yield:Row[];asOf:string};
const text=(v:unknown)=>v===null||v===undefined?'Unknown':typeof v==='object'?JSON.stringify(v):String(v);
const stamp=(v:unknown)=>typeof v==='string'?v.replace('T',' ').slice(0,19):'never';
const style={background:'var(--ds-bg-elev)',borderColor:'var(--ds-border)',color:'var(--ds-fg)'};
const link=(v:unknown)=>{try{const u=new URL(String(v));return ['http:','https:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}};
function Button({children,onClick,disabled=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button type="button" onClick={onClick} disabled={disabled} className="rounded border px-3 py-2 text-xs disabled:opacity-40" style={style}>{children}</button>;}
export default function IntelligenceOperator(){
  const [token,setToken]=useState(''),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[view,setView]=useState('sources');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<unknown>(null),[query,setQuery]=useState(''),[items,setItems]=useState<Row[]>([]);
  const [watchName,setWatchName]=useState(''),[instructions,setInstructions]=useState(''),[exclusions,setExclusions]=useState(''),[watchSources,setWatchSources]=useState('');
  const [sourceName,setSourceName]=useState(''),[sourceUrl,setSourceUrl]=useState(''),[adapter,setAdapter]=useState('rss'),[vertical,setVertical]=useState('oss'),[automatic,setAutomatic]=useState(false);
  const headers=()=>({Authorization:'Bearer '+token,'Content-Type':'application/json'});
  async function get(path:string){const r=await fetch('/api/admin/intelligence'+path,{headers:headers(),cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data;}
  async function reload(){setBusy(true);setError('');try{setSnapshot(await get(''));}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
  async function action(body:unknown){setBusy(true);setError('');try{const r=await fetch('/api/admin/intelligence',{method:'POST',headers:headers(),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed');setReceipt(d);setSnapshot(await get(''));}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(false);}}
  async function loadItems(next:string,watchId?:string){setView(next);setItems([]);setError('');setBusy(true);try{if(['funding','opportunities','corpus'].includes(next))setItems((await get('?view='+next+'&q='+encodeURIComponent(query))).items||[]);if(next==='watch-results')setItems((await get('?view=watch&id='+encodeURIComponent(watchId||''))).items||[]);}catch(e){setError(e instanceof Error?e.message:'Query failed');}finally{setBusy(false);}}
  async function trace(id:unknown){setBusy(true);try{setReceipt(await get('?view=trace&id='+encodeURIComponent(String(id))));}catch(e){setError(e instanceof Error?e.message:'Trace failed');}finally{setBusy(false);}}
  const button=(label:string,body:unknown)=><Button disabled={busy} onClick={()=>void action(body)}>{label}</Button>;
  const field=(label:string,value:string,set:(s:string)=>void,type='text')=><label className="block text-xs my-2">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} className="block w-full rounded border px-3 py-2 mt-1" style={style}/></label>;
  const rows=snapshot?.sources.filter(r=>(text(r.name)+' '+text(r.health)+' '+text(r.adapter)).toLowerCase().includes(query.toLowerCase()))||[];
  return <main className="max-w-7xl mx-auto p-4 sm:p-6 min-h-screen min-w-0 overflow-hidden" style={{color:'var(--ds-fg)',background:'var(--ds-bg-base)'}}>
    <div className="flex flex-wrap gap-4 items-center justify-between"><h1 className="text-xl font-semibold">Intelligence operator</h1><div className="flex gap-4 text-sm"><Link href="/app">Reader</Link><Link href="/app/corpus">Bounded backfill</Link><Link href="/admin">System admin</Link></div></div>
    <p className="text-sm mt-2 mb-4" style={{color:'var(--ds-fg-muted)'}}>Source evidence, corpus coverage, independent intelligence lanes and semantic watches. Reported availability requires source review.</p>
    {!snapshot?<form onSubmit={e=>{e.preventDefault();void reload();}} className="max-w-lg border rounded p-4" style={style}>
      {field('Admin bearer token',token,setToken,'password')}<button type="submit" disabled={busy} className="border rounded px-4 py-2" style={style}>Open operator</button><p className="text-xs mt-2">The token stays in this page’s memory and is never included in a URL.</p>
    </form>:<>
      <div className="flex gap-2 flex-wrap mb-4"><Button disabled={busy} onClick={()=>void reload()}>Refresh status</Button><Button onClick={()=>{setToken('');setSnapshot(null);setReceipt(null);setItems([]);}}>Lock</Button><span className="text-xs self-center">As of {stamp(snapshot.asOf)}</span></div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 my-4">{[['Configured sources',snapshot.sources.length],['Full first posts',snapshot.documents.full_bodies],['Body backlog',snapshot.documents.missing_bodies],['Partial legacy bodies',snapshot.documents.partial_bodies]].map(([label,value])=><div key={String(label)} className="border rounded p-3" style={style}><p className="text-xs">{String(label)}</p><strong className="text-xl">{text(value)}</strong></div>)}</div>
      <nav aria-label="Operator sections" className="flex gap-2 overflow-x-auto pb-3">{['sources','surfaces','corpus','funding','opportunities','watches','discovery','maintenance'].map(name=><button key={name} aria-pressed={view===name} onClick={()=>void loadItems(name)} className="border rounded px-3 py-2 text-sm whitespace-nowrap" style={style}>{name}</button>)}</nav>
      {field('Search sources or corpus',query,setQuery)}
      {['corpus','funding','opportunities'].includes(view)&&<Button disabled={busy} onClick={()=>void loadItems(view)}>Search {view}</Button>}
      {view==='sources'&&<>
        <details className="border rounded p-3 my-4" style={style}><summary>Add a public source</summary>
          <p className="text-xs mt-2">Use the public API endpoint for ATS boards. Registration does not submit applications or contact anyone.</p>
          {field('Source name',sourceName,setSourceName)}{field('Public URL',sourceUrl,setSourceUrl,'url')}
          <label className="text-xs">Adapter <select value={adapter} onChange={e=>setAdapter(e.target.value)} className="border rounded p-2 ml-2" style={style}>{['rss','greenhouse','lever','ashby','jsonld','program-page'].map(a=><option key={a}>{a}</option>)}</select></label>
          <label className="text-xs ml-4">Vertical <select value={vertical} onChange={e=>setVertical(e.target.value)} className="border rounded p-2 ml-2" style={style}>{['oss','ai','crypto'].map(a=><option key={a}>{a}</option>)}</select></label>
          <label className="block text-xs my-3"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/> Refresh through the existing ingestion cycle every six hours</label>
          {button('Register source',{action:'source',config:{name:sourceName,url:sourceUrl,adapter,vertical,enabled:true,autoRefresh:automatic,intervalSeconds:21600}})}
        </details>
        <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr>{['Source','Adapter / evidence','Health','Items','Last success','Controls'].map(s=><th className="text-left p-2" key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={text(r.source_key)} className="border-t" style={{borderColor:'var(--ds-border)'}}><td className="p-2"><a href={link(r.url)} target="_blank" rel="noreferrer">{text(r.name)}</a></td><td className="p-2">{text(r.adapter)}<br/>{text(r.evidence_scope)}</td><td className="p-2">{text(r.health)}{r.error_code?<p>{text(r.error_code)}</p>:null}</td><td className="p-2">{text(r.item_count)}</td><td className="p-2 whitespace-nowrap">{stamp(r.succeeded_at)}</td><td className="p-2 flex gap-2">{button(r.paused?'Resume':'Pause',{action:'pause-source',sourceKey:r.source_key,paused:!r.paused})}{r.managed_by==='operator'&&button('Ingest once',{action:'ingest',sourceKey:r.source_key})}</td></tr>)}</tbody></table></div>
      </>}
      {view==='surfaces'&&<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr>{['Source / surface','Acquisition lane','Status','Parsed','Success / retry eligible','Controls'].map(s=><th className="text-left p-2" key={s}>{s}</th>)}</tr></thead><tbody>{snapshot.surfaces.map(r=><tr key={text(r.surface_key)} className="border-t" style={{borderColor:'var(--ds-border)'}}><td className="p-2">{text(r.protocol)}<br/><a href={link(r.feed_url)} target="_blank" rel="noreferrer">{text(r.surface_slug)}</a></td><td className="p-2">{text(r.lane)}</td><td className="p-2">{text(r.status)} {text(r.http_status)}</td><td className="p-2">{text(r.parsed_items)}</td><td className="p-2">{stamp(r.succeeded_at)}<br/>{stamp(r.next_retry_at)}</td><td className="p-2 flex gap-2">{button('Probe once',{action:'probe',surfaceKey:r.surface_key})}{button(r.paused?'Resume':'Pause',{action:'pause-surface',surfaceKey:r.surface_key,paused:!r.paused})}</td></tr>)}</tbody></table></div>}
      {['corpus','funding','opportunities','watch-results'].includes(view)&&<div className="space-y-3 mt-4">{!busy&&!items.length&&<p className="text-sm">No matching records in this query window.</p>}{items.map(r=><article key={text(r.id||r.document_id)} className="border rounded p-4" style={style}><a href={link(r.url)} target="_blank" rel="noreferrer" className="font-medium text-sm">{text(r.title)}</a><p className="text-xs mt-2">{text(r.source_name)} · {text(r.body_status)} · {text(r.kind)} · {text(r.availability)} · {text(r.review_state)}</p><p className="text-sm mt-2">{text(r.evidence||r.excerpt||r.result)}</p><div className="flex gap-2 flex-wrap mt-3"><Button disabled={busy} onClick={()=>void trace(r.id||r.document_id)}>Trace evidence</Button>{view==='corpus'&&<>{button('Evaluate funding',{action:'classify',documentId:Number(r.id),lane:'funding'})}{button('Evaluate work',{action:'classify',documentId:Number(r.id),lane:'opportunities'})}</>}{['funding','opportunities'].includes(view)&&<>{button('Approve without email',{action:'review',documentId:Number(r.document_id),lane:view,decision:'approve',reason:'Operator reviewed the displayed source evidence and approved the record.'})}{button('Reject',{action:'review',documentId:Number(r.document_id),lane:view,decision:'reject',reason:'Operator rejected this record after source review.'})}{button('Withdraw',{action:'review',documentId:Number(r.document_id),lane:view,decision:'withdraw',reason:'Operator withdrew this record after source review.'})}</>}</div></article>)}</div>}
      {view==='watches'&&<div className="mt-4"><p className="text-sm">Watches evaluate meaning against stored full text. Runs are bounded and manual; matches never send email automatically.</p>
        {field('Watch name',watchName,setWatchName)}<label className="block text-xs mt-3">Matching instructions<textarea value={instructions} onChange={e=>setInstructions(e.target.value)} rows={4} className="block w-full border rounded p-3 mt-1" style={style}/></label>
        {field('Excluded phrases, one per comma',exclusions,setExclusions)}{field('Source keys, comma-separated; blank means all',watchSources,setWatchSources)}
        {button('Save watch',{action:'watch',definition:{name:watchName,instructions,sourceKeys:watchSources.split(',').map(s=>s.trim()).filter(Boolean),exclusions:exclusions.split(',').map(s=>s.trim()).filter(Boolean),enabled:true}})}
        {snapshot.watches.map(w=><article key={text(w.id)} className="border rounded p-4 mt-3" style={style}><h2 className="text-sm font-medium">{text(w.name)}</h2><p className="text-xs my-2">{text(w.instructions)}</p><div className="flex gap-2">{button('Evaluate next five',{action:'run-watch',id:w.id,limit:5})}<Button disabled={busy} onClick={()=>void loadItems('watch-results',String(w.id))}>View matches</Button>{!w.builtin&&button(w.enabled?'Disable':'Enable',{action:'watch',id:w.id,definition:{name:w.name,instructions:w.instructions,sourceKeys:w.source_keys,exclusions:w.exclusions,enabled:!w.enabled}})}</div></article>)}
      </div>}
      {view==='discovery'&&<div className="space-y-3 mt-4"><p className="text-sm">Candidate links are extracted from public documents. Reference counts indicate observed citations, not an endorsement. Candidates are never polled automatically.</p>{snapshot.discoveries.map(r=><article key={text(r.url)} className="border rounded p-3" style={style}><a href={link(r.url)} target="_blank" rel="noreferrer" className="text-sm break-all">{text(r.url)}</a><p className="text-xs my-2">{text(r.state)} · {text(r.source_references)} source references</p><div className="flex gap-2"><Button onClick={()=>{setSourceUrl(String(r.url));setSourceName(String(r.hostname));setView('sources');}}>Review as source</Button>{button('Reject',{action:'discovery',url:r.url,state:'rejected'})}{button('Mark dead',{action:'discovery',url:r.url,state:'dead'})}</div></article>)}</div>}
      {view==='maintenance'&&<div className="mt-4 space-y-4"><div className="flex flex-wrap gap-2">{button('Fetch six pending first posts',{action:'hydrate',limit:6})}{button('Classify five documents in both lanes',{action:'classify-batch',limit:5})}{button('Import next 100 legacy records',{action:'migrate',limit:100})}{button('Project bounded corpus into common index',{action:'import-pilot',limit:200})}</div><p className="text-xs">Backfills and migration do not reset notification watermarks. Model calls require a configured provider. Corpus counts separate full bodies from metadata and partial legacy excerpts.</p><h2 className="font-medium">Source yield</h2><pre className="text-xs overflow-auto border rounded p-3" style={style}>{JSON.stringify(snapshot.yield,null,2)}</pre><h2 className="font-medium">Classifier states</h2><pre className="text-xs overflow-auto border rounded p-3" style={style}>{JSON.stringify({evaluations:snapshot.evaluations,lanes:snapshot.lanes},null,2)}</pre></div>}
    </>}
    {busy&&<p role="status" className="text-sm mt-4">Running the requested operation…</p>}
    {error&&<div role="alert" data-testid="operator-error" className="border rounded p-3 mt-4" style={style}>{error}</div>}
    {receipt!==null&&<details open className="border rounded p-3 mt-4" style={style}><summary>Last operation / evidence trace</summary><pre className="text-xs overflow-auto max-h-96 mt-3 whitespace-pre-wrap break-words">{JSON.stringify(receipt,null,2)}</pre></details>}
  </main>;
}
